// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments_queries.sql

package conversation

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachmentByID = `-- name: attachmentByID :one
SELECT id, project_id, conversation_id, message_id, uploaded_by_member_id,
       filename, mime_type, size_bytes, storage_key, created_at
FROM attachments
WHERE id = $1
`

func (q *Queries) attachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, attachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConversationID,
		&i.MessageID,
		&i.UploadedByMemberID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const attachmentsByConversation = `-- name: attachmentsByConversation :many
SELECT id, project_id, conversation_id, message_id, uploaded_by_member_id,
       filename, mime_type, size_bytes, storage_key, created_at
FROM attachments
WHERE conversation_id = $1 AND message_id IS NOT NULL
ORDER BY created_at ASC
`

// All linked attachments for a conversation, for the join into message reads.
func (q *Queries) attachmentsByConversation(ctx context.Context, conversationID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, attachmentsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConversationID,
			&i.MessageID,
			&i.UploadedByMemberID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAttachment = `-- name: createAttachment :exec

INSERT INTO attachments (
    id, project_id, conversation_id, message_id, uploaded_by_member_id,
    filename, mime_type, size_bytes, storage_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type createAttachmentParams struct {
	ID                 uuid.UUID   `json:"id"`
	ProjectID          uuid.UUID   `json:"project_id"`
	ConversationID     uuid.UUID   `json:"conversation_id"`
	MessageID          pgtype.UUID `json:"message_id"`
	UploadedByMemberID pgtype.UUID `json:"uploaded_by_member_id"`
	Filename           string      `json:"filename"`
	MimeType           string      `json:"mime_type"`
	SizeBytes          int64       `json:"size_bytes"`
	StorageKey         string      `json:"storage_key"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createAttachment(ctx context.Context, arg createAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.ID,
		arg.ProjectID,
		arg.ConversationID,
		arg.MessageID,
		arg.UploadedByMemberID,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	return err
}

const linkAttachmentsToMessage = `-- name: linkAttachmentsToMessage :execrows
UPDATE attachments
SET message_id = $1
WHERE conversation_id = $2
  AND message_id IS NULL
  AND id = ANY($3::uuid[])
`

type linkAttachmentsToMessageParams struct {
	MessageID      pgtype.UUID `json:"message_id"`
	ConversationID uuid.UUID   `json:"conversation_id"`
	Column3        []uuid.UUID `json:"column_3"`
}

// Links a set of previously-uploaded, still-unlinked attachments to a message,
// scoped to the conversation so an id from another conversation can't be
// grafted on. Returns the rows affected so the caller can detect a mismatch.
func (q *Queries) linkAttachmentsToMessage(ctx context.Context, arg linkAttachmentsToMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkAttachmentsToMessage, arg.MessageID, arg.ConversationID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storageKeysByConversation = `-- name: storageKeysByConversation :many
SELECT storage_key
FROM attachments
WHERE conversation_id = $1
`

// Blob keys to delete when a conversation is hard-deleted (the rows cascade;
// the blobs are removed best-effort by the delete handler).
func (q *Queries) storageKeysByConversation(ctx context.Context, conversationID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, storageKeysByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
