// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_surfaces_queries.sql

package conversation

import (
	"context"

	"github.com/google/uuid"
)

const addSurfaceCoveredMember = `-- name: addSurfaceCoveredMember :exec
UPDATE conversation_surfaces
SET covered_member_ids = ARRAY(SELECT DISTINCT unnest(covered_member_ids || $2::uuid))
WHERE id = $1
`

type addSurfaceCoveredMemberParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 uuid.UUID `json:"column_2"`
}

// Appends memberID to the covered set, idempotently (no duplicates).
func (q *Queries) addSurfaceCoveredMember(ctx context.Context, arg addSurfaceCoveredMemberParams) error {
	_, err := q.db.Exec(ctx, addSurfaceCoveredMember, arg.ID, arg.Column2)
	return err
}

const createConversationSurface = `-- name: createConversationSurface :execrows

INSERT INTO conversation_surfaces (id, conversation_id, provider, kind, channel_id, thread_id, covered_member_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (conversation_id, provider) DO NOTHING
`

type createConversationSurfaceParams struct {
	ID               uuid.UUID   `json:"id"`
	ConversationID   uuid.UUID   `json:"conversation_id"`
	Provider         string      `json:"provider"`
	Kind             string      `json:"kind"`
	ChannelID        string      `json:"channel_id"`
	ThreadID         string      `json:"thread_id"`
	CoveredMemberIds []uuid.UUID `json:"covered_member_ids"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// ON CONFLICT DO NOTHING on (conversation_id, provider): a concurrent
// creation (event replay) affects zero rows — the caller re-reads the winner.
func (q *Queries) createConversationSurface(ctx context.Context, arg createConversationSurfaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, createConversationSurface,
		arg.ID,
		arg.ConversationID,
		arg.Provider,
		arg.Kind,
		arg.ChannelID,
		arg.ThreadID,
		arg.CoveredMemberIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelWebhook = `-- name: getChannelWebhook :one
SELECT channel_id, webhook_id, webhook_token
FROM discord_channel_webhooks
WHERE channel_id = $1
`

type getChannelWebhookRow struct {
	ChannelID    string `json:"channel_id"`
	WebhookID    string `json:"webhook_id"`
	WebhookToken string `json:"webhook_token"`
}

func (q *Queries) getChannelWebhook(ctx context.Context, channelID string) (getChannelWebhookRow, error) {
	row := q.db.QueryRow(ctx, getChannelWebhook, channelID)
	var i getChannelWebhookRow
	err := row.Scan(&i.ChannelID, &i.WebhookID, &i.WebhookToken)
	return i, err
}

const markSurfaceArchived = `-- name: markSurfaceArchived :execrows
UPDATE conversation_surfaces
SET archived_at = NOW()
WHERE id = $1 AND archived_at IS NULL
`

// CAS on archived_at so a duplicate CLOSED replay archives exactly once.
func (q *Queries) markSurfaceArchived(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSurfaceArchived, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const surfaceByChannelThread = `-- name: surfaceByChannelThread :one
SELECT id, conversation_id, provider, kind, channel_id, thread_id, covered_member_ids, created_at, archived_at
FROM conversation_surfaces
WHERE provider = $1 AND channel_id = $2 AND thread_id = $3
`

type surfaceByChannelThreadParams struct {
	Provider  string `json:"provider"`
	ChannelID string `json:"channel_id"`
	ThreadID  string `json:"thread_id"`
}

// Inbound correlation for Slack/Telegram: (thread_ts / message_id) is unique
// only WITHIN a channel/chat, so the lookup keys on (provider, channel_id,
// thread_id), not thread_id alone.
func (q *Queries) surfaceByChannelThread(ctx context.Context, arg surfaceByChannelThreadParams) (ConversationSurface, error) {
	row := q.db.QueryRow(ctx, surfaceByChannelThread, arg.Provider, arg.ChannelID, arg.ThreadID)
	var i ConversationSurface
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Provider,
		&i.Kind,
		&i.ChannelID,
		&i.ThreadID,
		&i.CoveredMemberIds,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const surfaceByConversationProvider = `-- name: surfaceByConversationProvider :one
SELECT id, conversation_id, provider, kind, channel_id, thread_id, covered_member_ids, created_at, archived_at
FROM conversation_surfaces
WHERE conversation_id = $1 AND provider = $2
`

type surfaceByConversationProviderParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Provider       string    `json:"provider"`
}

func (q *Queries) surfaceByConversationProvider(ctx context.Context, arg surfaceByConversationProviderParams) (ConversationSurface, error) {
	row := q.db.QueryRow(ctx, surfaceByConversationProvider, arg.ConversationID, arg.Provider)
	var i ConversationSurface
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Provider,
		&i.Kind,
		&i.ChannelID,
		&i.ThreadID,
		&i.CoveredMemberIds,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const surfaceByThread = `-- name: surfaceByThread :one
SELECT id, conversation_id, provider, kind, channel_id, thread_id, covered_member_ids, created_at, archived_at
FROM conversation_surfaces
WHERE provider = $1 AND thread_id = $2
`

type surfaceByThreadParams struct {
	Provider string `json:"provider"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) surfaceByThread(ctx context.Context, arg surfaceByThreadParams) (ConversationSurface, error) {
	row := q.db.QueryRow(ctx, surfaceByThread, arg.Provider, arg.ThreadID)
	var i ConversationSurface
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Provider,
		&i.Kind,
		&i.ChannelID,
		&i.ThreadID,
		&i.CoveredMemberIds,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertChannelWebhook = `-- name: upsertChannelWebhook :exec
INSERT INTO discord_channel_webhooks (channel_id, webhook_id, webhook_token)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id) DO UPDATE
SET webhook_id = EXCLUDED.webhook_id, webhook_token = EXCLUDED.webhook_token
`

type upsertChannelWebhookParams struct {
	ChannelID    string `json:"channel_id"`
	WebhookID    string `json:"webhook_id"`
	WebhookToken string `json:"webhook_token"`
}

// Last writer wins: a webhook recreated after a manual deletion simply
// replaces the stale cached pair.
func (q *Queries) upsertChannelWebhook(ctx context.Context, arg upsertChannelWebhookParams) error {
	_, err := q.db.Exec(ctx, upsertChannelWebhook, arg.ChannelID, arg.WebhookID, arg.WebhookToken)
	return err
}

const upsertCorrelationSurface = `-- name: upsertCorrelationSurface :exec
INSERT INTO conversation_surfaces (id, conversation_id, provider, kind, channel_id, thread_id, covered_member_ids)
VALUES ($1, $2, $3, 'thread', $4, $5, '{}')
ON CONFLICT (conversation_id, provider) DO UPDATE
SET channel_id = EXCLUDED.channel_id,
    thread_id  = EXCLUDED.thread_id
`

type upsertCorrelationSurfaceParams struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	Provider       string    `json:"provider"`
	ChannelID      string    `json:"channel_id"`
	ThreadID       string    `json:"thread_id"`
}

// Records/updates the direct-ask correlation surface a provider writes after an
// outbound Deliver (Slack channel+thread_ts, Telegram chat+message_id). Last
// writer wins on (conversation_id, provider) — a re-delivery overwrites the
// channel/thread, matching the pre-surface flat-column UPDATE.
func (q *Queries) upsertCorrelationSurface(ctx context.Context, arg upsertCorrelationSurfaceParams) error {
	_, err := q.db.Exec(ctx, upsertCorrelationSurface,
		arg.ID,
		arg.ConversationID,
		arg.Provider,
		arg.ChannelID,
		arg.ThreadID,
	)
	return err
}
