// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations_queries.sql

package conversation

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const conversationByID = `-- name: conversationByID :one
SELECT id, project_id, asker_member_id, responder_member_id,
       status, question, title, context,
       summary, tags, entities,
       created_at, updated_at
FROM conversations
WHERE id = $1
`

type conversationByIDRow struct {
	ID                uuid.UUID   `json:"id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	AskerMemberID     uuid.UUID   `json:"asker_member_id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
	Status            string      `json:"status"`
	Question          string      `json:"question"`
	Title             string      `json:"title"`
	Context           string      `json:"context"`
	Summary           string      `json:"summary"`
	Tags              []string    `json:"tags"`
	Entities          []string    `json:"entities"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

func (q *Queries) conversationByID(ctx context.Context, id uuid.UUID) (conversationByIDRow, error) {
	row := q.db.QueryRow(ctx, conversationByID, id)
	var i conversationByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AskerMemberID,
		&i.ResponderMemberID,
		&i.Status,
		&i.Question,
		&i.Title,
		&i.Context,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConversation = `-- name: createConversation :one

INSERT INTO conversations (
    id, project_id, asker_member_id, responder_member_id,
    status, question, title, context,
    summary, tags, entities
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, project_id, asker_member_id, responder_member_id,
          status, question, title, context,
          summary, tags, entities,
          created_at, updated_at
`

type createConversationParams struct {
	ID                uuid.UUID   `json:"id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	AskerMemberID     uuid.UUID   `json:"asker_member_id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
	Status            string      `json:"status"`
	Question          string      `json:"question"`
	Title             string      `json:"title"`
	Context           string      `json:"context"`
	Summary           string      `json:"summary"`
	Tags              []string    `json:"tags"`
	Entities          []string    `json:"entities"`
}

type createConversationRow struct {
	ID                uuid.UUID   `json:"id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	AskerMemberID     uuid.UUID   `json:"asker_member_id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
	Status            string      `json:"status"`
	Question          string      `json:"question"`
	Title             string      `json:"title"`
	Context           string      `json:"context"`
	Summary           string      `json:"summary"`
	Tags              []string    `json:"tags"`
	Entities          []string    `json:"entities"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createConversation(ctx context.Context, arg createConversationParams) (createConversationRow, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.ProjectID,
		arg.AskerMemberID,
		arg.ResponderMemberID,
		arg.Status,
		arg.Question,
		arg.Title,
		arg.Context,
		arg.Summary,
		arg.Tags,
		arg.Entities,
	)
	var i createConversationRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AskerMemberID,
		&i.ResponderMemberID,
		&i.Status,
		&i.Question,
		&i.Title,
		&i.Context,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationMetadata = `-- name: updateConversationMetadata :one
UPDATE conversations
SET summary    = $2,
    tags       = $3,
    entities   = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, asker_member_id, responder_member_id,
          status, question, title, context,
          summary, tags, entities,
          created_at, updated_at
`

type updateConversationMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Summary  string    `json:"summary"`
	Tags     []string  `json:"tags"`
	Entities []string  `json:"entities"`
}

type updateConversationMetadataRow struct {
	ID                uuid.UUID   `json:"id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	AskerMemberID     uuid.UUID   `json:"asker_member_id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
	Status            string      `json:"status"`
	Question          string      `json:"question"`
	Title             string      `json:"title"`
	Context           string      `json:"context"`
	Summary           string      `json:"summary"`
	Tags              []string    `json:"tags"`
	Entities          []string    `json:"entities"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

func (q *Queries) updateConversationMetadata(ctx context.Context, arg updateConversationMetadataParams) (updateConversationMetadataRow, error) {
	row := q.db.QueryRow(ctx, updateConversationMetadata,
		arg.ID,
		arg.Summary,
		arg.Tags,
		arg.Entities,
	)
	var i updateConversationMetadataRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AskerMemberID,
		&i.ResponderMemberID,
		&i.Status,
		&i.Question,
		&i.Title,
		&i.Context,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationStatus = `-- name: updateConversationStatus :one
UPDATE conversations
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, asker_member_id, responder_member_id,
          status, question, title, context,
          summary, tags, entities,
          created_at, updated_at
`

type updateConversationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

type updateConversationStatusRow struct {
	ID                uuid.UUID   `json:"id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	AskerMemberID     uuid.UUID   `json:"asker_member_id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
	Status            string      `json:"status"`
	Question          string      `json:"question"`
	Title             string      `json:"title"`
	Context           string      `json:"context"`
	Summary           string      `json:"summary"`
	Tags              []string    `json:"tags"`
	Entities          []string    `json:"entities"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

func (q *Queries) updateConversationStatus(ctx context.Context, arg updateConversationStatusParams) (updateConversationStatusRow, error) {
	row := q.db.QueryRow(ctx, updateConversationStatus, arg.ID, arg.Status)
	var i updateConversationStatusRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AskerMemberID,
		&i.ResponderMemberID,
		&i.Status,
		&i.Question,
		&i.Title,
		&i.Context,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
