// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_members_queries.sql

package conversation

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeCandidatesByConversations = `-- name: activeCandidatesByConversations :many
SELECT conversation_id, member_id
FROM conversation_members
WHERE conversation_id = ANY($1::uuid[])
  AND invited_at IS NOT NULL
  AND excluded_at IS NULL
ORDER BY invited_at ASC
`

type activeCandidatesByConversationsRow struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberID       uuid.UUID `json:"member_id"`
}

// Still-active pool candidates (dispatched, not excluded) for a batch of
// conversations.
func (q *Queries) activeCandidatesByConversations(ctx context.Context, dollar_1 []uuid.UUID) ([]activeCandidatesByConversationsRow, error) {
	rows, err := q.db.Query(ctx, activeCandidatesByConversations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []activeCandidatesByConversationsRow{}
	for rows.Next() {
		var i activeCandidatesByConversationsRow
		if err := rows.Scan(&i.ConversationID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addConversationCandidate = `-- name: addConversationCandidate :exec


INSERT INTO conversation_members (conversation_id, member_id, invited_at)
VALUES ($1, $2, NOW())
ON CONFLICT (conversation_id, member_id)
DO UPDATE SET invited_at = COALESCE(conversation_members.invited_at, NOW())
`

type addConversationCandidateParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberID       uuid.UUID `json:"member_id"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// conversation_members is the single membership table: one row per
// (conversation, member), carrying how they joined. invited_at marks a
// dispatched pool candidate (ex-conversation_candidates); added_at marks an
// explicitly added participant (ex-conversation_participants). A member can be
// both — one row, both column sets.
//
//	active candidate     = invited_at IS NOT NULL AND excluded_at IS NULL
//	explicit participant = added_at   IS NOT NULL
//
// Dispatch: add member to the pool, idempotently. A re-dispatch keeps the
// original invited_at (COALESCE), and never clears an existing exclusion.
func (q *Queries) addConversationCandidate(ctx context.Context, arg addConversationCandidateParams) error {
	_, err := q.db.Exec(ctx, addConversationCandidate, arg.ConversationID, arg.MemberID)
	return err
}

const addParticipant = `-- name: addParticipant :exec
INSERT INTO conversation_members (conversation_id, member_id, added_at, added_by)
VALUES ($1, $2, NOW(), $3)
ON CONFLICT (conversation_id, member_id)
DO UPDATE SET added_at = COALESCE(conversation_members.added_at, NOW()),
              added_by = COALESCE(conversation_members.added_by, EXCLUDED.added_by)
`

type addParticipantParams struct {
	ConversationID uuid.UUID   `json:"conversation_id"`
	MemberID       uuid.UUID   `json:"member_id"`
	AddedBy        pgtype.UUID `json:"added_by"`
}

// Explicitly add member to the thread, idempotently. A re-add keeps the
// original added_at/added_by (COALESCE); a member already in the pool as a
// candidate gets added_at stamped on the same row (becomes both).
func (q *Queries) addParticipant(ctx context.Context, arg addParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.MemberID, arg.AddedBy)
	return err
}

const candidatesByConversation = `-- name: candidatesByConversation :many
SELECT member_id, invited_at, excluded_at
FROM conversation_members
WHERE conversation_id = $1 AND invited_at IS NOT NULL
ORDER BY invited_at ASC
`

type candidatesByConversationRow struct {
	MemberID   uuid.UUID          `json:"member_id"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	ExcludedAt pgtype.Timestamptz `json:"excluded_at"`
}

// All pool candidates (dispatched), excluded ones included. Pure participants
// (invited_at IS NULL) are not candidates.
func (q *Queries) candidatesByConversation(ctx context.Context, conversationID uuid.UUID) ([]candidatesByConversationRow, error) {
	rows, err := q.db.Query(ctx, candidatesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []candidatesByConversationRow{}
	for rows.Next() {
		var i candidatesByConversationRow
		if err := rows.Scan(&i.MemberID, &i.InvitedAt, &i.ExcludedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const excludeConversationCandidate = `-- name: excludeConversationCandidate :exec
UPDATE conversation_members
SET excluded_at = NOW()
WHERE conversation_id = $1 AND member_id = $2 AND invited_at IS NOT NULL
`

type excludeConversationCandidateParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberID       uuid.UUID `json:"member_id"`
}

// Release a candidate from the pool. Scoped to rows that were actually
// dispatched so a pure participant row is never stamped excluded.
func (q *Queries) excludeConversationCandidate(ctx context.Context, arg excludeConversationCandidateParams) error {
	_, err := q.db.Exec(ctx, excludeConversationCandidate, arg.ConversationID, arg.MemberID)
	return err
}

const isActiveCandidate = `-- name: isActiveCandidate :one
SELECT EXISTS(
  SELECT 1 FROM conversation_members
  WHERE conversation_id = $1 AND member_id = $2
    AND invited_at IS NOT NULL AND excluded_at IS NULL
) AS active
`

type isActiveCandidateParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberID       uuid.UUID `json:"member_id"`
}

// Still an active (dispatched, not excluded) pool candidate — i.e. on the
// conversation's distribution list as a candidate, not merely a participant.
func (q *Queries) isActiveCandidate(ctx context.Context, arg isActiveCandidateParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveCandidate, arg.ConversationID, arg.MemberID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const openPoolConversationsForMember = `-- name: openPoolConversationsForMember :many
SELECT c.id, c.project_id, c.asker_member_id, c.responder_member_id,
       c.status, c.question, c.title, c.context,
       c.summary, c.tags, c.entities,
       c.created_at, c.updated_at
FROM conversations c
JOIN conversation_members cc ON cc.conversation_id = c.id
WHERE cc.member_id = $1
  AND cc.invited_at IS NOT NULL
  AND cc.excluded_at IS NULL
  AND c.responder_member_id IS NULL
  AND c.status = 'open'
ORDER BY c.created_at DESC
`

type openPoolConversationsForMemberRow struct {
	ID                uuid.UUID   `json:"id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	AskerMemberID     uuid.UUID   `json:"asker_member_id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
	Status            string      `json:"status"`
	Question          string      `json:"question"`
	Title             string      `json:"title"`
	Context           string      `json:"context"`
	Summary           string      `json:"summary"`
	Tags              []string    `json:"tags"`
	Entities          []string    `json:"entities"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

// Unanswered pool conversations the member was contacted on (inbox "awaiting
// an answer"). Only active candidacies count — a pure participant row does not
// put a conversation in the member's pool inbox.
func (q *Queries) openPoolConversationsForMember(ctx context.Context, memberID uuid.UUID) ([]openPoolConversationsForMemberRow, error) {
	rows, err := q.db.Query(ctx, openPoolConversationsForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []openPoolConversationsForMemberRow{}
	for rows.Next() {
		var i openPoolConversationsForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AskerMemberID,
			&i.ResponderMemberID,
			&i.Status,
			&i.Question,
			&i.Title,
			&i.Context,
			&i.Summary,
			&i.Tags,
			&i.Entities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participantsByConversation = `-- name: participantsByConversation :many
SELECT conversation_id, member_id, added_by, added_at
FROM conversation_members
WHERE conversation_id = $1 AND added_at IS NOT NULL
ORDER BY added_at ASC
`

type participantsByConversationRow struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	MemberID       uuid.UUID          `json:"member_id"`
	AddedBy        pgtype.UUID        `json:"added_by"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
}

// Explicitly-added participants only (the asker and assigned responder are
// implicit and not stored here).
func (q *Queries) participantsByConversation(ctx context.Context, conversationID uuid.UUID) ([]participantsByConversationRow, error) {
	rows, err := q.db.Query(ctx, participantsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []participantsByConversationRow{}
	for rows.Next() {
		var i participantsByConversationRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.MemberID,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participantsByConversations = `-- name: participantsByConversations :many
SELECT conversation_id, member_id, added_by, added_at
FROM conversation_members
WHERE conversation_id = ANY($1::uuid[]) AND added_at IS NOT NULL
ORDER BY added_at ASC
`

type participantsByConversationsRow struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	MemberID       uuid.UUID          `json:"member_id"`
	AddedBy        pgtype.UUID        `json:"added_by"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
}

func (q *Queries) participantsByConversations(ctx context.Context, dollar_1 []uuid.UUID) ([]participantsByConversationsRow, error) {
	rows, err := q.db.Query(ctx, participantsByConversations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []participantsByConversationsRow{}
	for rows.Next() {
		var i participantsByConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.MemberID,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMembersByDomains = `-- name: projectMembersByDomains :many
SELECT pm.member_id
FROM project_members pm
JOIN members m ON m.id = pm.member_id
WHERE pm.project_id = $1
  AND m.status = 'active'
  AND pm.domains && $2::text[]
  AND pm.member_id <> $3
`

type projectMembersByDomainsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   []string  `json:"column_2"`
	MemberID  uuid.UUID `json:"member_id"`
}

// Candidate resolution at dispatch: active project members whose expertise
// intersects the requested domains, excluding the asker.
func (q *Queries) projectMembersByDomains(ctx context.Context, arg projectMembersByDomainsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, projectMembersByDomains, arg.ProjectID, arg.Column2, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var member_id uuid.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFirstResponder = `-- name: recordFirstResponder :execrows
UPDATE conversations
SET responder_member_id = $2,
    updated_at           = NOW()
WHERE id = $1 AND responder_member_id IS NULL
`

type recordFirstResponderParams struct {
	ID                uuid.UUID   `json:"id"`
	ResponderMemberID pgtype.UUID `json:"responder_member_id"`
}

// Records who first answered, for KB attribution: a compare-and-set so only the
// FIRST answerer is written (first writer wins; a later answer affects zero
// rows). Not a claim and not a gate — anyone on the conversation can still
// reply; this only remembers the first responder.
func (q *Queries) recordFirstResponder(ctx context.Context, arg recordFirstResponderParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordFirstResponder, arg.ID, arg.ResponderMemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
