// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: escalation_queries.sql

package conversation

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const markConversationAlerted = `-- name: markConversationAlerted :execrows
UPDATE conversations
SET alerted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND alerted_at IS NULL
`

// CAS marker so the alert-channel post fires exactly once even across
// concurrent sweeps.
func (q *Queries) markConversationAlerted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markConversationAlerted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConversationExpired = `-- name: markConversationExpired :execrows
UPDATE conversations
SET status     = 'timed_out',
    updated_at = NOW()
WHERE id = $1 AND status = 'open' AND responder_member_id IS NULL
`

// CAS transition to timed_out: the conversation is abandoned (no responder ever
// answered) and past the expiry timeout. Guarded on the current state so the
// transition fires exactly once even across concurrent sweeps and never races a
// late answer — the moment a responder is stamped or the status leaves 'open',
// this affects zero rows.
func (q *Queries) markConversationExpired(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markConversationExpired, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConversationNudged = `-- name: markConversationNudged :execrows
UPDATE conversations
SET nudged_at  = NOW(),
    updated_at = NOW()
WHERE id = $1 AND nudged_at IS NULL
`

// CAS marker so a nudge fires exactly once even across concurrent sweeps.
func (q *Queries) markConversationNudged(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markConversationNudged, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orgEscalationSettings = `-- name: orgEscalationSettings :one

SELECT claim_timeout_seconds, alert_timeout_seconds, default_alert_channel_id
FROM organizations
WHERE id = $1
`

type orgEscalationSettingsRow struct {
	ClaimTimeoutSeconds   pgtype.Int8 `json:"claim_timeout_seconds"`
	AlertTimeoutSeconds   pgtype.Int8 `json:"alert_timeout_seconds"`
	DefaultAlertChannelID string      `json:"default_alert_channel_id"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// Escalation sweep: the two rules the minute ticker evaluates. Timeouts are
// resolved per organization at sweep time: NULL column = product default
// (the $1 parameter), 0 = rule disabled for that org. Projects without an
// org (nullable projects.org_id) fall back to the default too.
func (q *Queries) orgEscalationSettings(ctx context.Context, id uuid.UUID) (orgEscalationSettingsRow, error) {
	row := q.db.QueryRow(ctx, orgEscalationSettings, id)
	var i orgEscalationSettingsRow
	err := row.Scan(&i.ClaimTimeoutSeconds, &i.AlertTimeoutSeconds, &i.DefaultAlertChannelID)
	return i, err
}

const unclaimedForAlert = `-- name: unclaimedForAlert :many
SELECT c.id, c.project_id, c.question, c.title, c.created_at,
       COALESCE(pp.alert_channel_ids, '{}'::text[]) AS project_alert_channel_ids,
       COALESCE(pp.kind, '') AS project_alert_kind,
       COALESCE(o.default_alert_channel_id, '') AS org_alert_channel_id,
       (
         SELECT COUNT(*) FROM conversation_members cc
         WHERE cc.conversation_id = c.id
           AND cc.invited_at IS NOT NULL AND cc.excluded_at IS NULL
       ) AS candidate_count
FROM conversations c
JOIN projects p ON p.id = c.project_id
LEFT JOIN organizations o ON o.id = p.org_id
LEFT JOIN LATERAL (
    SELECT kind, alert_channel_ids
    FROM project_providers
    WHERE project_id = c.project_id
    ORDER BY (cardinality(alert_channel_ids) > 0) DESC, updated_at DESC
    LIMIT 1
) pp ON true
WHERE c.responder_member_id IS NULL
  AND c.status = 'open'
  AND c.alerted_at IS NULL
  AND EXISTS (
    SELECT 1 FROM conversation_members cc
    WHERE cc.conversation_id = c.id AND cc.invited_at IS NOT NULL
  )
  AND COALESCE(o.alert_timeout_seconds, $1) > 0
  AND c.created_at < NOW() - make_interval(secs => COALESCE(o.alert_timeout_seconds, $1))
ORDER BY c.created_at ASC
`

type unclaimedForAlertRow struct {
	ID                     uuid.UUID `json:"id"`
	ProjectID              uuid.UUID `json:"project_id"`
	Question               string    `json:"question"`
	Title                  string    `json:"title"`
	CreatedAt              time.Time `json:"created_at"`
	ProjectAlertChannelIds []string  `json:"project_alert_channel_ids"`
	ProjectAlertKind       string    `json:"project_alert_kind"`
	OrgAlertChannelID      string    `json:"org_alert_channel_id"`
	CandidateCount         int64     `json:"candidate_count"`
}

// Pool conversations past their org's alert timeout that were never posted to
// the alert channel. Resolves both channel candidates (project's own
// alert_channel_id, org default_alert_channel_id fallback), the provider kind
// that owns the project's alert channel, and the active candidate count in
// the same round trip, so the sweeper needs no further lookups before
// posting.
//
// The per-project provider row is picked by preferring one that actually has
// an alert_channel_id configured (a provider re-saved without one — e.g.
// rotating a Telegram bot token — must never shadow another provider's
// configured alert channel), tiebroken deterministically by updated_at DESC.
// When no configured provider has an alert_channel_id, the most recently
// updated row is still returned (its empty alert_channel_id) so the org
// default_alert_channel_id fallback below is unaffected; project_alert_kind
// is still that row's kind, and the caller posts the org-fallback channel
// through it too (empty only when the project has no provider configured at
// all).
//
// project_alert_kind is the (project, kind) key the caller must resolve the
// ChannelPoster by — review fit#4: a project with several provider kinds
// configured must post through the one this query picked, never an
// ambiguous "the project's provider" lookup that ignores kind entirely.
func (q *Queries) unclaimedForAlert(ctx context.Context, alertTimeoutSeconds pgtype.Int8) ([]unclaimedForAlertRow, error) {
	rows, err := q.db.Query(ctx, unclaimedForAlert, alertTimeoutSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []unclaimedForAlertRow{}
	for rows.Next() {
		var i unclaimedForAlertRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Question,
			&i.Title,
			&i.CreatedAt,
			&i.ProjectAlertChannelIds,
			&i.ProjectAlertKind,
			&i.OrgAlertChannelID,
			&i.CandidateCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unclaimedForExpiry = `-- name: unclaimedForExpiry :many
SELECT c.id, c.project_id, c.asker_member_id, c.question, c.context, c.created_at
FROM conversations c
JOIN projects p ON p.id = c.project_id
LEFT JOIN organizations o ON o.id = p.org_id
WHERE c.responder_member_id IS NULL
  AND c.status = 'open'
  AND EXISTS (
    SELECT 1 FROM conversation_members cc
    WHERE cc.conversation_id = c.id AND cc.invited_at IS NOT NULL
  )
  AND COALESCE(o.alert_timeout_seconds, $1) > 0
  AND c.created_at < NOW() - make_interval(secs => COALESCE(o.alert_timeout_seconds, $1) * $2)
ORDER BY c.created_at ASC
`

type unclaimedForExpiryParams struct {
	AlertTimeoutSeconds   pgtype.Int8 `json:"alert_timeout_seconds"`
	AlertTimeoutSeconds_2 pgtype.Int8 `json:"alert_timeout_seconds_2"`
}

type unclaimedForExpiryRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	AskerMemberID uuid.UUID `json:"asker_member_id"`
	Question      string    `json:"question"`
	Context       string    `json:"context"`
	CreatedAt     time.Time `json:"created_at"`
}

// Pool conversations that sat open with no responder past the EXPIRY timeout —
// the third and final escalation rung. There is no dedicated expiry column: the
// expiry threshold is the org's effective alert timeout ($1 fills in the
// product default when the org stored none) multiplied by $2 (the product
// expiry multiplier). A resolved alert timeout of 0 disables the org's alerts
// and, with it, expiry — a conversation the org chose never to alert on is
// never auto-expired either. The once-only guard is the status transition
// itself (markConversationExpired flips status off 'open'), so no marker column
// is needed; the WHERE below simply lists still-open, still-unassigned pool
// conversations old enough to expire.
func (q *Queries) unclaimedForExpiry(ctx context.Context, arg unclaimedForExpiryParams) ([]unclaimedForExpiryRow, error) {
	rows, err := q.db.Query(ctx, unclaimedForExpiry, arg.AlertTimeoutSeconds, arg.AlertTimeoutSeconds_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []unclaimedForExpiryRow{}
	for rows.Next() {
		var i unclaimedForExpiryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AskerMemberID,
			&i.Question,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unclaimedForNudge = `-- name: unclaimedForNudge :many
SELECT c.id, c.project_id, c.asker_member_id, c.question, c.context, c.created_at
FROM conversations c
JOIN projects p ON p.id = c.project_id
LEFT JOIN organizations o ON o.id = p.org_id
WHERE c.responder_member_id IS NULL
  AND c.status = 'open'
  AND c.nudged_at IS NULL
  AND EXISTS (
    SELECT 1 FROM conversation_members cc
    WHERE cc.conversation_id = c.id AND cc.invited_at IS NOT NULL
  )
  AND COALESCE(o.claim_timeout_seconds, $1) > 0
  AND c.created_at < NOW() - make_interval(secs => COALESCE(o.claim_timeout_seconds, $1))
ORDER BY c.created_at ASC
`

type unclaimedForNudgeRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	AskerMemberID uuid.UUID `json:"asker_member_id"`
	Question      string    `json:"question"`
	Context       string    `json:"context"`
	CreatedAt     time.Time `json:"created_at"`
}

// Pool conversations past their org's nudge timeout (stored column keeps the
// legacy claim_timeout_seconds name) that were never nudged. "Unanswered" =
// no specialist label stamped yet (first answer stamps it).
func (q *Queries) unclaimedForNudge(ctx context.Context, claimTimeoutSeconds pgtype.Int8) ([]unclaimedForNudgeRow, error) {
	rows, err := q.db.Query(ctx, unclaimedForNudge, claimTimeoutSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []unclaimedForNudgeRow{}
	for rows.Next() {
		var i unclaimedForNudgeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AskerMemberID,
			&i.Question,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgEscalationSettings = `-- name: updateOrgEscalationSettings :exec
UPDATE organizations
SET claim_timeout_seconds    = $2,
    alert_timeout_seconds    = COALESCE($3, alert_timeout_seconds),
    default_alert_channel_id = CASE
        WHEN $4::text = '' THEN default_alert_channel_id
        WHEN $4::text = '-' THEN ''
        ELSE $4::text
    END,
    updated_at               = NOW()
WHERE id = $1
`

type updateOrgEscalationSettingsParams struct {
	ID                  uuid.UUID   `json:"id"`
	ClaimTimeoutSeconds pgtype.Int8 `json:"claim_timeout_seconds"`
	AlertTimeoutSeconds pgtype.Int8 `json:"alert_timeout_seconds"`
	Column4             string      `json:"column_4"`
}

// default_alert_channel_id: empty string leaves the stored value unchanged,
// the literal "-" clears it (mirrors UpdateOrganizationSettingsRequest's wire
// convention for the field). alert_timeout_seconds: a NULL $3 parameter
// leaves the stored value unchanged (optional int64 presence — an absent
// field must not silently disable alerts); a non-NULL $3, including 0,
// overwrites it (0 disables the rule).
func (q *Queries) updateOrgEscalationSettings(ctx context.Context, arg updateOrgEscalationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateOrgEscalationSettings,
		arg.ID,
		arg.ClaimTimeoutSeconds,
		arg.AlertTimeoutSeconds,
		arg.Column4,
	)
	return err
}
