// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_queries.sql

package conversation

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMessage = `-- name: addMessage :one

INSERT INTO messages (id, conversation_id, author_member_id, role, body, source, agent_client)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, conversation_id, author_member_id, role, body, created_at, source, agent_client
`

type addMessageParams struct {
	ID             uuid.UUID   `json:"id"`
	ConversationID uuid.UUID   `json:"conversation_id"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Role           string      `json:"role"`
	Body           string      `json:"body"`
	Source         string      `json:"source"`
	AgentClient    string      `json:"agent_client"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) addMessage(ctx context.Context, arg addMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, addMessage,
		arg.ID,
		arg.ConversationID,
		arg.AuthorMemberID,
		arg.Role,
		arg.Body,
		arg.Source,
		arg.AgentClient,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorMemberID,
		&i.Role,
		&i.Body,
		&i.CreatedAt,
		&i.Source,
		&i.AgentClient,
	)
	return i, err
}

const memberNamesByIDs = `-- name: memberNamesByIDs :many
SELECT
    id,
    COALESCE(
        NULLIF(BTRIM(display_name), ''),
        NULLIF(BTRIM(CONCAT_WS(' ', first_name, last_name)), ''),
        NULLIF(BTRIM(email), ''),
        LEFT(id::text, 8)
    )::text AS display_name
FROM members
WHERE id = ANY($1::uuid[])
`

type memberNamesByIDsRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) memberNamesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]memberNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, memberNamesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []memberNamesByIDsRow{}
	for rows.Next() {
		var i memberNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesByConversation = `-- name: messagesByConversation :many
SELECT id, conversation_id, author_member_id, role, body, created_at, source, agent_client
FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) messagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AuthorMemberID,
			&i.Role,
			&i.Body,
			&i.CreatedAt,
			&i.Source,
			&i.AgentClient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
