// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package conversation

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID                 uuid.UUID   `json:"id"`
	ProjectID          uuid.UUID   `json:"project_id"`
	ConversationID     uuid.UUID   `json:"conversation_id"`
	MessageID          pgtype.UUID `json:"message_id"`
	UploadedByMemberID pgtype.UUID `json:"uploaded_by_member_id"`
	Filename           string      `json:"filename"`
	MimeType           string      `json:"mime_type"`
	SizeBytes          int64       `json:"size_bytes"`
	StorageKey         string      `json:"storage_key"`
	CreatedAt          time.Time   `json:"created_at"`
}

type ConversationSurface struct {
	ID               uuid.UUID          `json:"id"`
	ConversationID   uuid.UUID          `json:"conversation_id"`
	Provider         string             `json:"provider"`
	Kind             string             `json:"kind"`
	ChannelID        string             `json:"channel_id"`
	ThreadID         string             `json:"thread_id"`
	CoveredMemberIds []uuid.UUID        `json:"covered_member_ids"`
	CreatedAt        time.Time          `json:"created_at"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
}

type Message struct {
	ID             uuid.UUID   `json:"id"`
	ConversationID uuid.UUID   `json:"conversation_id"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Role           string      `json:"role"`
	Body           string      `json:"body"`
	CreatedAt      time.Time   `json:"created_at"`
	Source         string      `json:"source"`
	AgentClient    string      `json:"agent_client"`
}
