// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package conversation

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Still-active pool candidates (dispatched, not excluded) for a batch of
	// conversations.
	activeCandidatesByConversations(ctx context.Context, dollar_1 []uuid.UUID) ([]activeCandidatesByConversationsRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// conversation_members is the single membership table: one row per
	// (conversation, member), carrying how they joined. invited_at marks a
	// dispatched pool candidate (ex-conversation_candidates); added_at marks an
	// explicitly added participant (ex-conversation_participants). A member can be
	// both — one row, both column sets.
	//
	//   active candidate     = invited_at IS NOT NULL AND excluded_at IS NULL
	//   explicit participant = added_at   IS NOT NULL
	// Dispatch: add member to the pool, idempotently. A re-dispatch keeps the
	// original invited_at (COALESCE), and never clears an existing exclusion.
	addConversationCandidate(ctx context.Context, arg addConversationCandidateParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	addMessage(ctx context.Context, arg addMessageParams) (Message, error)
	// Explicitly add member to the thread, idempotently. A re-add keeps the
	// original added_at/added_by (COALESCE); a member already in the pool as a
	// candidate gets added_at stamped on the same row (becomes both).
	addParticipant(ctx context.Context, arg addParticipantParams) error
	// Appends memberID to the covered set, idempotently (no duplicates).
	addSurfaceCoveredMember(ctx context.Context, arg addSurfaceCoveredMemberParams) error
	attachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error)
	// All linked attachments for a conversation, for the join into message reads.
	attachmentsByConversation(ctx context.Context, conversationID uuid.UUID) ([]Attachment, error)
	// All pool candidates (dispatched), excluded ones included. Pure participants
	// (invited_at IS NULL) are not candidates.
	candidatesByConversation(ctx context.Context, conversationID uuid.UUID) ([]candidatesByConversationRow, error)
	conversationByID(ctx context.Context, id uuid.UUID) (conversationByIDRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createAttachment(ctx context.Context, arg createAttachmentParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createConversation(ctx context.Context, arg createConversationParams) (createConversationRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// ON CONFLICT DO NOTHING on (conversation_id, provider): a concurrent
	// creation (event replay) affects zero rows — the caller re-reads the winner.
	createConversationSurface(ctx context.Context, arg createConversationSurfaceParams) (int64, error)
	// Release a candidate from the pool. Scoped to rows that were actually
	// dispatched so a pure participant row is never stamped excluded.
	excludeConversationCandidate(ctx context.Context, arg excludeConversationCandidateParams) error
	getChannelWebhook(ctx context.Context, channelID string) (getChannelWebhookRow, error)
	// Still an active (dispatched, not excluded) pool candidate — i.e. on the
	// conversation's distribution list as a candidate, not merely a participant.
	isActiveCandidate(ctx context.Context, arg isActiveCandidateParams) (bool, error)
	// Links a set of previously-uploaded, still-unlinked attachments to a message,
	// scoped to the conversation so an id from another conversation can't be
	// grafted on. Returns the rows affected so the caller can detect a mismatch.
	linkAttachmentsToMessage(ctx context.Context, arg linkAttachmentsToMessageParams) (int64, error)
	// CAS marker so the alert-channel post fires exactly once even across
	// concurrent sweeps.
	markConversationAlerted(ctx context.Context, id uuid.UUID) (int64, error)
	// CAS transition to timed_out: the conversation is abandoned (no responder ever
	// answered) and past the expiry timeout. Guarded on the current state so the
	// transition fires exactly once even across concurrent sweeps and never races a
	// late answer — the moment a responder is stamped or the status leaves 'open',
	// this affects zero rows.
	markConversationExpired(ctx context.Context, id uuid.UUID) (int64, error)
	// CAS marker so a nudge fires exactly once even across concurrent sweeps.
	markConversationNudged(ctx context.Context, id uuid.UUID) (int64, error)
	// CAS on archived_at so a duplicate CLOSED replay archives exactly once.
	markSurfaceArchived(ctx context.Context, id uuid.UUID) (int64, error)
	memberNamesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]memberNamesByIDsRow, error)
	messagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error)
	// Unanswered pool conversations the member was contacted on (inbox "awaiting
	// an answer"). Only active candidacies count — a pure participant row does not
	// put a conversation in the member's pool inbox.
	openPoolConversationsForMember(ctx context.Context, memberID uuid.UUID) ([]openPoolConversationsForMemberRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Escalation sweep: the two rules the minute ticker evaluates. Timeouts are
	// resolved per organization at sweep time: NULL column = product default
	// (the $1 parameter), 0 = rule disabled for that org. Projects without an
	// org (nullable projects.org_id) fall back to the default too.
	orgEscalationSettings(ctx context.Context, id uuid.UUID) (orgEscalationSettingsRow, error)
	// Explicitly-added participants only (the asker and assigned responder are
	// implicit and not stored here).
	participantsByConversation(ctx context.Context, conversationID uuid.UUID) ([]participantsByConversationRow, error)
	participantsByConversations(ctx context.Context, dollar_1 []uuid.UUID) ([]participantsByConversationsRow, error)
	// Candidate resolution at dispatch: active project members whose expertise
	// intersects the requested domains, excluding the asker.
	projectMembersByDomains(ctx context.Context, arg projectMembersByDomainsParams) ([]uuid.UUID, error)
	// Records who first answered, for KB attribution: a compare-and-set so only the
	// FIRST answerer is written (first writer wins; a later answer affects zero
	// rows). Not a claim and not a gate — anyone on the conversation can still
	// reply; this only remembers the first responder.
	recordFirstResponder(ctx context.Context, arg recordFirstResponderParams) (int64, error)
	// Blob keys to delete when a conversation is hard-deleted (the rows cascade;
	// the blobs are removed best-effort by the delete handler).
	storageKeysByConversation(ctx context.Context, conversationID uuid.UUID) ([]string, error)
	// Inbound correlation for Slack/Telegram: (thread_ts / message_id) is unique
	// only WITHIN a channel/chat, so the lookup keys on (provider, channel_id,
	// thread_id), not thread_id alone.
	surfaceByChannelThread(ctx context.Context, arg surfaceByChannelThreadParams) (ConversationSurface, error)
	surfaceByConversationProvider(ctx context.Context, arg surfaceByConversationProviderParams) (ConversationSurface, error)
	surfaceByThread(ctx context.Context, arg surfaceByThreadParams) (ConversationSurface, error)
	// Pool conversations past their org's alert timeout that were never posted to
	// the alert channel. Resolves both channel candidates (project's own
	// alert_channel_id, org default_alert_channel_id fallback), the provider kind
	// that owns the project's alert channel, and the active candidate count in
	// the same round trip, so the sweeper needs no further lookups before
	// posting.
	//
	// The per-project provider row is picked by preferring one that actually has
	// an alert_channel_id configured (a provider re-saved without one — e.g.
	// rotating a Telegram bot token — must never shadow another provider's
	// configured alert channel), tiebroken deterministically by updated_at DESC.
	// When no configured provider has an alert_channel_id, the most recently
	// updated row is still returned (its empty alert_channel_id) so the org
	// default_alert_channel_id fallback below is unaffected; project_alert_kind
	// is still that row's kind, and the caller posts the org-fallback channel
	// through it too (empty only when the project has no provider configured at
	// all).
	//
	// project_alert_kind is the (project, kind) key the caller must resolve the
	// ChannelPoster by — review fit#4: a project with several provider kinds
	// configured must post through the one this query picked, never an
	// ambiguous "the project's provider" lookup that ignores kind entirely.
	unclaimedForAlert(ctx context.Context, alertTimeoutSeconds pgtype.Int8) ([]unclaimedForAlertRow, error)
	// Pool conversations that sat open with no responder past the EXPIRY timeout —
	// the third and final escalation rung. There is no dedicated expiry column: the
	// expiry threshold is the org's effective alert timeout ($1 fills in the
	// product default when the org stored none) multiplied by $2 (the product
	// expiry multiplier). A resolved alert timeout of 0 disables the org's alerts
	// and, with it, expiry — a conversation the org chose never to alert on is
	// never auto-expired either. The once-only guard is the status transition
	// itself (markConversationExpired flips status off 'open'), so no marker column
	// is needed; the WHERE below simply lists still-open, still-unassigned pool
	// conversations old enough to expire.
	unclaimedForExpiry(ctx context.Context, arg unclaimedForExpiryParams) ([]unclaimedForExpiryRow, error)
	// Pool conversations past their org's nudge timeout (stored column keeps the
	// legacy claim_timeout_seconds name) that were never nudged. "Unanswered" =
	// no specialist label stamped yet (first answer stamps it).
	unclaimedForNudge(ctx context.Context, claimTimeoutSeconds pgtype.Int8) ([]unclaimedForNudgeRow, error)
	updateConversationMetadata(ctx context.Context, arg updateConversationMetadataParams) (updateConversationMetadataRow, error)
	updateConversationStatus(ctx context.Context, arg updateConversationStatusParams) (updateConversationStatusRow, error)
	// default_alert_channel_id: empty string leaves the stored value unchanged,
	// the literal "-" clears it (mirrors UpdateOrganizationSettingsRequest's wire
	// convention for the field). alert_timeout_seconds: a NULL $3 parameter
	// leaves the stored value unchanged (optional int64 presence — an absent
	// field must not silently disable alerts); a non-NULL $3, including 0,
	// overwrites it (0 disables the rule).
	updateOrgEscalationSettings(ctx context.Context, arg updateOrgEscalationSettingsParams) error
	// Last writer wins: a webhook recreated after a manual deletion simply
	// replaces the stale cached pair.
	upsertChannelWebhook(ctx context.Context, arg upsertChannelWebhookParams) error
	// Records/updates the direct-ask correlation surface a provider writes after an
	// outbound Deliver (Slack channel+thread_ts, Telegram chat+message_id). Last
	// writer wins on (conversation_id, provider) — a re-delivery overwrites the
	// channel/thread, matching the pre-surface flat-column UPDATE.
	upsertCorrelationSurface(ctx context.Context, arg upsertCorrelationSurfaceParams) error
}

var _ Querier = (*Queries)(nil)
