// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge_queries.sql

package knowledge

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateKnowledgeEntry = `-- name: activateKnowledgeEntry :one
UPDATE knowledge_entries
SET status     = 'active',
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, project_id, question, answer,
          summary, tags, entities, author_member_id, source, status,
          created_at, updated_at
`

type activateKnowledgeEntryRow struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Question       string      `json:"question"`
	Answer         string      `json:"answer"`
	Summary        string      `json:"summary"`
	Tags           []string    `json:"tags"`
	Entities       []string    `json:"entities"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Source         string      `json:"source"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

// Flip an entry to status='active' and bump updated_at ("last reviewed"). Shared
// by ApproveKnowledgeEntry (an agent-suggested pending entry a human vetted) and
// RevalidateKnowledgeEntry (a stale entry re-confirmed as current).
func (q *Queries) activateKnowledgeEntry(ctx context.Context, id uuid.UUID) (activateKnowledgeEntryRow, error) {
	row := q.db.QueryRow(ctx, activateKnowledgeEntry, id)
	var i activateKnowledgeEntryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Question,
		&i.Answer,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.AuthorMemberID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKnowledgeEntry = `-- name: createKnowledgeEntry :one

INSERT INTO knowledge_entries (
    id, org_id, project_id, question, answer,
    summary, tags, entities, author_member_id, source, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, project_id, question, answer,
          summary, tags, entities, author_member_id, source, status,
          created_at, updated_at
`

type createKnowledgeEntryParams struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Question       string      `json:"question"`
	Answer         string      `json:"answer"`
	Summary        string      `json:"summary"`
	Tags           []string    `json:"tags"`
	Entities       []string    `json:"entities"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Source         string      `json:"source"`
	Status         string      `json:"status"`
}

type createKnowledgeEntryRow struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Question       string      `json:"question"`
	Answer         string      `json:"answer"`
	Summary        string      `json:"summary"`
	Tags           []string    `json:"tags"`
	Entities       []string    `json:"entities"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Source         string      `json:"source"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createKnowledgeEntry(ctx context.Context, arg createKnowledgeEntryParams) (createKnowledgeEntryRow, error) {
	row := q.db.QueryRow(ctx, createKnowledgeEntry,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Question,
		arg.Answer,
		arg.Summary,
		arg.Tags,
		arg.Entities,
		arg.AuthorMemberID,
		arg.Source,
		arg.Status,
	)
	var i createKnowledgeEntryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Question,
		&i.Answer,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.AuthorMemberID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKnowledgeEntry = `-- name: deleteKnowledgeEntry :exec
DELETE FROM knowledge_entries
WHERE id = $1
`

func (q *Queries) deleteKnowledgeEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeEntry, id)
	return err
}

const knowledgeEntryByID = `-- name: knowledgeEntryByID :one
SELECT id, org_id, project_id, question, answer,
       summary, tags, entities, author_member_id, source, status,
       created_at, updated_at
FROM knowledge_entries
WHERE id = $1
`

type knowledgeEntryByIDRow struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Question       string      `json:"question"`
	Answer         string      `json:"answer"`
	Summary        string      `json:"summary"`
	Tags           []string    `json:"tags"`
	Entities       []string    `json:"entities"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Source         string      `json:"source"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) knowledgeEntryByID(ctx context.Context, id uuid.UUID) (knowledgeEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, knowledgeEntryByID, id)
	var i knowledgeEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Question,
		&i.Answer,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.AuthorMemberID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markKnowledgeEntryStale = `-- name: markKnowledgeEntryStale :one
UPDATE knowledge_entries
SET status     = 'stale',
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, project_id, question, answer,
          summary, tags, entities, author_member_id, source, status,
          created_at, updated_at
`

type markKnowledgeEntryStaleRow struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Question       string      `json:"question"`
	Answer         string      `json:"answer"`
	Summary        string      `json:"summary"`
	Tags           []string    `json:"tags"`
	Entities       []string    `json:"entities"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Source         string      `json:"source"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) markKnowledgeEntryStale(ctx context.Context, id uuid.UUID) (markKnowledgeEntryStaleRow, error) {
	row := q.db.QueryRow(ctx, markKnowledgeEntryStale, id)
	var i markKnowledgeEntryStaleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Question,
		&i.Answer,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.AuthorMemberID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKnowledgeEntry = `-- name: updateKnowledgeEntry :one
UPDATE knowledge_entries
SET question   = $2,
    answer     = $3,
    summary    = $4,
    tags       = $5,
    entities   = $6,
    status     = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, project_id, question, answer,
          summary, tags, entities, author_member_id, source, status,
          created_at, updated_at
`

type updateKnowledgeEntryParams struct {
	ID       uuid.UUID `json:"id"`
	Question string    `json:"question"`
	Answer   string    `json:"answer"`
	Summary  string    `json:"summary"`
	Tags     []string  `json:"tags"`
	Entities []string  `json:"entities"`
	Status   string    `json:"status"`
}

type updateKnowledgeEntryRow struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Question       string      `json:"question"`
	Answer         string      `json:"answer"`
	Summary        string      `json:"summary"`
	Tags           []string    `json:"tags"`
	Entities       []string    `json:"entities"`
	AuthorMemberID pgtype.UUID `json:"author_member_id"`
	Source         string      `json:"source"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) updateKnowledgeEntry(ctx context.Context, arg updateKnowledgeEntryParams) (updateKnowledgeEntryRow, error) {
	row := q.db.QueryRow(ctx, updateKnowledgeEntry,
		arg.ID,
		arg.Question,
		arg.Answer,
		arg.Summary,
		arg.Tags,
		arg.Entities,
		arg.Status,
	)
	var i updateKnowledgeEntryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Question,
		&i.Answer,
		&i.Summary,
		&i.Tags,
		&i.Entities,
		&i.AuthorMemberID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
