// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package knowledge

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Flip an entry to status='active' and bump updated_at ("last reviewed"). Shared
	// by ApproveKnowledgeEntry (an agent-suggested pending entry a human vetted) and
	// RevalidateKnowledgeEntry (a stale entry re-confirmed as current).
	activateKnowledgeEntry(ctx context.Context, id uuid.UUID) (activateKnowledgeEntryRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createKnowledgeEntry(ctx context.Context, arg createKnowledgeEntryParams) (createKnowledgeEntryRow, error)
	deleteKnowledgeEntry(ctx context.Context, id uuid.UUID) error
	knowledgeEntryByID(ctx context.Context, id uuid.UUID) (knowledgeEntryByIDRow, error)
	markKnowledgeEntryStale(ctx context.Context, id uuid.UUID) (markKnowledgeEntryStaleRow, error)
	updateKnowledgeEntry(ctx context.Context, arg updateKnowledgeEntryParams) (updateKnowledgeEntryRow, error)
}

var _ Querier = (*Queries)(nil)
