// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventlog_queries.sql

package eventlog

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: appendEvent :one

INSERT INTO event_log (id, project_id, seq, type, payload, occurred_at)
VALUES (
    $1,
    $2,
    (SELECT COALESCE(MAX(seq), 0) + 1 FROM event_log WHERE project_id = $2),
    $3,
    $4,
    $5
)
RETURNING id, project_id, seq, type, payload, occurred_at, created_at, global_seq
`

type appendEventParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	Type       string    `json:"type"`
	Payload    []byte    `json:"payload"`
	OccurredAt time.Time `json:"occurred_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// appendEvent inserts one event at the next per-project sequence position. The
// subselect derives seq atomically within the insert; the (project_id, seq)
// unique constraint turns a concurrent race into a conflict the adapter maps
// to a sentinel rather than a silent duplicate.
func (q *Queries) appendEvent(ctx context.Context, arg appendEventParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Payload,
		arg.OccurredAt,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.GlobalSeq,
	)
	return i, err
}

const eventsAfterGlobalSeq = `-- name: eventsAfterGlobalSeq :many
SELECT global_seq, id, project_id, seq, type, payload, occurred_at, created_at
FROM event_log
WHERE global_seq > $1
ORDER BY global_seq ASC
LIMIT $2
`

type eventsAfterGlobalSeqParams struct {
	GlobalSeq pgtype.Int8 `json:"global_seq"`
	Limit     int32       `json:"limit"`
}

type eventsAfterGlobalSeqRow struct {
	GlobalSeq  pgtype.Int8 `json:"global_seq"`
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	Seq        int64       `json:"seq"`
	Type       string      `json:"type"`
	Payload    []byte      `json:"payload"`
	OccurredAt time.Time   `json:"occurred_at"`
	CreatedAt  time.Time   `json:"created_at"`
}

// Ordered replay window for the outbox relay (E1): events the bus may not have
// delivered before a restart, above a subscriber's watermark.
func (q *Queries) eventsAfterGlobalSeq(ctx context.Context, arg eventsAfterGlobalSeqParams) ([]eventsAfterGlobalSeqRow, error) {
	rows, err := q.db.Query(ctx, eventsAfterGlobalSeq, arg.GlobalSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []eventsAfterGlobalSeqRow{}
	for rows.Next() {
		var i eventsAfterGlobalSeqRow
		if err := rows.Scan(
			&i.GlobalSeq,
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsByProjectSince = `-- name: eventsByProjectSince :many
SELECT id, project_id, seq, type, payload, occurred_at, created_at, global_seq
FROM event_log
WHERE project_id = $1 AND seq > $2
ORDER BY seq ASC
`

type eventsByProjectSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Seq       int64     `json:"seq"`
}

func (q *Queries) eventsByProjectSince(ctx context.Context, arg eventsByProjectSinceParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, eventsByProjectSince, arg.ProjectID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.GlobalSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
