// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projector_offsets_queries.sql

package eventlog

import (
	"context"
)

const advanceProjectorOffset = `-- name: advanceProjectorOffset :execrows
UPDATE projector_offsets
SET last_global_seq = $1, updated_at = NOW()
WHERE subscriber = $2 AND last_global_seq = $3
`

type advanceProjectorOffsetParams struct {
	ToSeq      int64  `json:"to_seq"`
	Subscriber string `json:"subscriber"`
	FromSeq    int64  `json:"from_seq"`
}

// Contiguous advance used by the publish hot path: moves the watermark forward
// only when it currently sits at from_seq, so a concurrent/out-of-order publish
// can never let the watermark skip an un-delivered event (the relay's ordered
// catch-up fills any gap). Rows affected = 0 means "not contiguous, leave it for
// the relay".
func (q *Queries) advanceProjectorOffset(ctx context.Context, arg advanceProjectorOffsetParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceProjectorOffset, arg.ToSeq, arg.Subscriber, arg.FromSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectorOffset = `-- name: getProjectorOffset :one

SELECT last_global_seq FROM projector_offsets WHERE subscriber = $1
`

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) getProjectorOffset(ctx context.Context, subscriber string) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectorOffset, subscriber)
	var last_global_seq int64
	err := row.Scan(&last_global_seq)
	return last_global_seq, err
}

const seedProjectorOffset = `-- name: seedProjectorOffset :exec
INSERT INTO projector_offsets (subscriber, last_global_seq, updated_at)
SELECT $1, COALESCE(MAX(global_seq), 0), NOW() FROM event_log
ON CONFLICT (subscriber) DO NOTHING
`

// Seed a subscriber's watermark to the current head of the log so a first-ever
// boot does NOT replay (and re-deliver) the entire historical log. No-op once
// the subscriber already has an offset.
func (q *Queries) seedProjectorOffset(ctx context.Context, subscriber string) error {
	_, err := q.db.Exec(ctx, seedProjectorOffset, subscriber)
	return err
}

const upsertProjectorOffset = `-- name: upsertProjectorOffset :exec
INSERT INTO projector_offsets (subscriber, last_global_seq, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (subscriber) DO UPDATE
SET last_global_seq = EXCLUDED.last_global_seq, updated_at = NOW()
`

type upsertProjectorOffsetParams struct {
	Subscriber    string `json:"subscriber"`
	LastGlobalSeq int64  `json:"last_global_seq"`
}

func (q *Queries) upsertProjectorOffset(ctx context.Context, arg upsertProjectorOffsetParams) error {
	_, err := q.db.Exec(ctx, upsertProjectorOffset, arg.Subscriber, arg.LastGlobalSeq)
	return err
}
