// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventlog

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EventLog struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	Seq        int64       `json:"seq"`
	Type       string      `json:"type"`
	Payload    []byte      `json:"payload"`
	OccurredAt time.Time   `json:"occurred_at"`
	CreatedAt  time.Time   `json:"created_at"`
	GlobalSeq  pgtype.Int8 `json:"global_seq"`
}
