// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventlog

import (
	"context"
)

type Querier interface {
	// Contiguous advance used by the publish hot path: moves the watermark forward
	// only when it currently sits at from_seq, so a concurrent/out-of-order publish
	// can never let the watermark skip an un-delivered event (the relay's ordered
	// catch-up fills any gap). Rows affected = 0 means "not contiguous, leave it for
	// the relay".
	advanceProjectorOffset(ctx context.Context, arg advanceProjectorOffsetParams) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// appendEvent inserts one event at the next per-project sequence position. The
	// subselect derives seq atomically within the insert; the (project_id, seq)
	// unique constraint turns a concurrent race into a conflict the adapter maps
	// to a sentinel rather than a silent duplicate.
	appendEvent(ctx context.Context, arg appendEventParams) (EventLog, error)
	// Ordered replay window for the outbox relay (E1): events the bus may not have
	// delivered before a restart, above a subscriber's watermark.
	eventsAfterGlobalSeq(ctx context.Context, arg eventsAfterGlobalSeqParams) ([]eventsAfterGlobalSeqRow, error)
	eventsByProjectSince(ctx context.Context, arg eventsByProjectSinceParams) ([]EventLog, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	getProjectorOffset(ctx context.Context, subscriber string) (int64, error)
	// Seed a subscriber's watermark to the current head of the log so a first-ever
	// boot does NOT replay (and re-deliver) the entire historical log. No-op once
	// the subscriber already has an offset.
	seedProjectorOffset(ctx context.Context, subscriber string) error
	upsertProjectorOffset(ctx context.Context, arg upsertProjectorOffsetParams) error
}

var _ Querier = (*Queries)(nil)
