// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts_queries.sql

package identity

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountByEmail = `-- name: accountByEmail :one
SELECT id, subject, email, display_name, created_at, updated_at, password_hash, password_reset_version
FROM accounts
WHERE email = $1
`

func (q *Queries) accountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, accountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordResetVersion,
	)
	return i, err
}

const accountByID = `-- name: accountByID :one
SELECT id, subject, email, display_name, created_at, updated_at, password_hash, password_reset_version
FROM accounts
WHERE id = $1
`

func (q *Queries) accountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, accountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordResetVersion,
	)
	return i, err
}

const accountBySubject = `-- name: accountBySubject :one
SELECT id, subject, email, display_name, created_at, updated_at, password_hash, password_reset_version
FROM accounts
WHERE subject = $1
`

func (q *Queries) accountBySubject(ctx context.Context, subject pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, accountBySubject, subject)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordResetVersion,
	)
	return i, err
}

const accountCredentialByEmail = `-- name: accountCredentialByEmail :one
SELECT id, password_hash
FROM accounts
WHERE email = $1
`

type accountCredentialByEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

// Returns the id + password hash for email+password login. password_hash is NULL
// for IdP-only accounts (the caller must treat that as "no local password").
func (q *Queries) accountCredentialByEmail(ctx context.Context, email string) (accountCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, accountCredentialByEmail, email)
	var i accountCredentialByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const accountResetVersionByEmail = `-- name: accountResetVersionByEmail :one
SELECT id, password_reset_version
FROM accounts
WHERE email = $1 AND password_hash IS NOT NULL
`

type accountResetVersionByEmailRow struct {
	ID                   uuid.UUID `json:"id"`
	PasswordResetVersion int32     `json:"password_reset_version"`
}

// The current password_reset_version for a local account, keyed by email. Used to
// stamp a reset token so it can be invalidated (single-use / on password change).
func (q *Queries) accountResetVersionByEmail(ctx context.Context, email string) (accountResetVersionByEmailRow, error) {
	row := q.db.QueryRow(ctx, accountResetVersionByEmail, email)
	var i accountResetVersionByEmailRow
	err := row.Scan(&i.ID, &i.PasswordResetVersion)
	return i, err
}

const createAccount = `-- name: createAccount :one

INSERT INTO accounts (id, subject, email, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, subject, email, display_name, created_at, updated_at, password_hash, password_reset_version
`

type createAccountParams struct {
	ID          uuid.UUID   `json:"id"`
	Subject     pgtype.Text `json:"subject"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createAccount(ctx context.Context, arg createAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordResetVersion,
	)
	return i, err
}

const resetAccountPassword = `-- name: resetAccountPassword :one
UPDATE accounts
SET password_hash = $1,
    password_reset_version = password_reset_version + 1,
    updated_at = NOW()
WHERE email = $2
  AND password_reset_version = $3::bigint
  AND password_hash IS NOT NULL
RETURNING id
`

type resetAccountPasswordParams struct {
	PasswordHash    pgtype.Text `json:"password_hash"`
	Email           string      `json:"email"`
	ExpectedVersion int64       `json:"expected_version"`
}

// Atomically spends a reset-token version while replacing the password. A
// concurrent replay, unknown account, or IdP-only account returns no row.
func (q *Queries) resetAccountPassword(ctx context.Context, arg resetAccountPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resetAccountPassword, arg.PasswordHash, arg.Email, arg.ExpectedVersion)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setAccountPassword = `-- name: setAccountPassword :exec
UPDATE accounts
SET password_hash = $2,
    password_reset_version = password_reset_version + 1,
    updated_at    = NOW()
WHERE id = $1
`

type setAccountPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

// Sets (or clears) the bcrypt password hash for a local-auth account.
func (q *Queries) setAccountPassword(ctx context.Context, arg setAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, setAccountPassword, arg.ID, arg.PasswordHash)
	return err
}
