// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: join_tokens_queries.sql

package identity

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeJoinTokenByOrg = `-- name: activeJoinTokenByOrg :one
SELECT token, org_id, project_id, created_at
FROM org_join_tokens
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type activeJoinTokenByOrgRow struct {
	Token     string    `json:"token"`
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

// The org's current live token, if any. adaptererr.ErrNotFound (no row) when the
// org has never generated one or the last one was revoked.
func (q *Queries) activeJoinTokenByOrg(ctx context.Context, orgID uuid.UUID) (activeJoinTokenByOrgRow, error) {
	row := q.db.QueryRow(ctx, activeJoinTokenByOrg, orgID)
	var i activeJoinTokenByOrgRow
	err := row.Scan(
		&i.Token,
		&i.OrgID,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinToken = `-- name: createJoinToken :exec

INSERT INTO org_join_tokens (token, org_id, project_id, created_by_member_id)
VALUES ($1, $2, $3, $4)
`

type createJoinTokenParams struct {
	Token             string      `json:"token"`
	OrgID             uuid.UUID   `json:"org_id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	CreatedByMemberID pgtype.UUID `json:"created_by_member_id"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// Inserts a fresh join token. The caller (CreateJoinToken store method) revokes
// any prior live token for the org in the same transaction first, so the partial
// unique index (one live token per org) is never violated.
func (q *Queries) createJoinToken(ctx context.Context, arg createJoinTokenParams) error {
	_, err := q.db.Exec(ctx, createJoinToken,
		arg.Token,
		arg.OrgID,
		arg.ProjectID,
		arg.CreatedByMemberID,
	)
	return err
}

const joinTokenByToken = `-- name: joinTokenByToken :one
SELECT org_id, project_id, (revoked_at IS NOT NULL)::bool AS revoked
FROM org_join_tokens
WHERE token = $1
`

type joinTokenByTokenRow struct {
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Revoked   bool      `json:"revoked"`
}

// Resolves a token to its org/project and whether it has been revoked. The
// org/project a redemption lands in come ONLY from this row.
func (q *Queries) joinTokenByToken(ctx context.Context, token string) (joinTokenByTokenRow, error) {
	row := q.db.QueryRow(ctx, joinTokenByToken, token)
	var i joinTokenByTokenRow
	err := row.Scan(&i.OrgID, &i.ProjectID, &i.Revoked)
	return i, err
}

const revokeLiveOrgJoinTokens = `-- name: revokeLiveOrgJoinTokens :execrows
UPDATE org_join_tokens
SET revoked_at = NOW()
WHERE org_id = $1 AND revoked_at IS NULL
`

// Revokes the org's live (non-revoked) token(s). Used both to rotate before a
// fresh insert and by an explicit revoke. Idempotent: revokes nothing when the
// org has no live token.
func (q *Queries) revokeLiveOrgJoinTokens(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveOrgJoinTokens, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
