// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members_queries.sql

package identity

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMemberOnboardingDismissed = `-- name: clearMemberOnboardingDismissed :execrows
UPDATE members
SET onboarding_dismissed_at = NULL, updated_at = NOW()
WHERE id = $1
`

// Undo the dismissal (the Get-started page + nav item come back).
func (q *Queries) clearMemberOnboardingDismissed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearMemberOnboardingDismissed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMember = `-- name: createMember :one

INSERT INTO members (id, email, display_name, slack_user_id, telegram_chat_id, delivery_channel, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
`

type createMemberParams struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
}

type createMemberRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createMember(ctx context.Context, arg createMemberParams) (createMemberRow, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.SlackUserID,
		arg.TelegramChatID,
		arg.DeliveryChannel,
		arg.Status,
	)
	var i createMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const createMemberWithAccount = `-- name: createMemberWithAccount :exec
INSERT INTO members (id, display_name, delivery_channel, status, account_id, email)
VALUES ($1, $2, $3, $4, $5, $6)
`

type createMemberWithAccountParams struct {
	ID              uuid.UUID   `json:"id"`
	DisplayName     pgtype.Text `json:"display_name"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	AccountID       pgtype.UUID `json:"account_id"`
	Email           pgtype.Text `json:"email"`
}

// Creates a member linked to a human account (active, dashboard-channel). Used by
// the CreateOrganization compound store; the account must exist before calling this.
func (q *Queries) createMemberWithAccount(ctx context.Context, arg createMemberWithAccountParams) error {
	_, err := q.db.Exec(ctx, createMemberWithAccount,
		arg.ID,
		arg.DisplayName,
		arg.DeliveryChannel,
		arg.Status,
		arg.AccountID,
		arg.Email,
	)
	return err
}

const listOrgRoster = `-- name: listOrgRoster :many
SELECT
    m.id, m.email, m.display_name, m.first_name, m.last_name, m.git_handle,
    m.delivery_channel, m.slack_user_id, m.teams_user_id, m.telegram_chat_id,
    m.discord_user_id, m.binding_error, m.status, m.return_date,
    (m.account_id IS NULL)::bool AS external,
    COALESCE(om.role = 'admin', false)::bool AS is_org_admin,
    COALESCE(
        json_agg(json_build_object('project_id', pm.project_id, 'domains', pm.domains))
            FILTER (WHERE pm.project_id IS NOT NULL),
        '[]'
    )::jsonb AS projects
FROM members m
JOIN project_members pm ON pm.member_id = m.id
JOIN projects p ON p.id = pm.project_id AND p.org_id = $1
LEFT JOIN org_members om ON om.account_id = m.account_id AND om.org_id = $1
WHERE CASE
        WHEN $2::bool THEN m.status = 'pending'
        ELSE m.status NOT IN ('removed', 'purged', 'pending')
      END
GROUP BY m.id, om.role
`

type listOrgRosterParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	PendingOnly bool        `json:"pending_only"`
}

type listOrgRosterRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	DeliveryChannel string      `json:"delivery_channel"`
	SlackUserID     string      `json:"slack_user_id"`
	TeamsUserID     string      `json:"teams_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
	Status          string      `json:"status"`
	ReturnDate      pgtype.Date `json:"return_date"`
	External        bool        `json:"external"`
	IsOrgAdmin      bool        `json:"is_org_admin"`
	Projects        []byte      `json:"projects"`
}

// Rich org roster: every member participating in one of the org's projects, with
// identity, channel + bindings, status, return_date, org-admin flag, external
// flag, and their per-project expertise tags as a JSON array of
// {project_id, domains}. The pendingOnly flag ($2) splits the two complementary
// audiences from one query body:
//   - pendingOnly = false → the roster everyone sees: removed/purged AND the
//     `pending` self-join redeemers (join-code, awaiting approval) are excluded.
//   - pendingOnly = true  → admin-only: ONLY the `pending` members, backing the
//     Team page's "Invited" group.
//
// The application handler calls it twice (see list_members.go) and appends the
// pending set to the roster only for an org admin (RBAC gate in server.go).
func (q *Queries) listOrgRoster(ctx context.Context, arg listOrgRosterParams) ([]listOrgRosterRow, error) {
	rows, err := q.db.Query(ctx, listOrgRoster, arg.OrgID, arg.PendingOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []listOrgRosterRow{}
	for rows.Next() {
		var i listOrgRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.GitHandle,
			&i.DeliveryChannel,
			&i.SlackUserID,
			&i.TeamsUserID,
			&i.TelegramChatID,
			&i.DiscordUserID,
			&i.BindingError,
			&i.Status,
			&i.ReturnDate,
			&i.External,
			&i.IsOrgAdmin,
			&i.Projects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberAccountID = `-- name: memberAccountID :one
SELECT account_id FROM members WHERE id = $1
`

func (q *Queries) memberAccountID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, memberAccountID, id)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const memberByAccountID = `-- name: memberByAccountID :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE account_id = $1
ORDER BY (status IN ('removed', 'purged', 'deactivated', 'suspended')) ASC, created_at DESC
LIMIT 1
`

type memberByAccountIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

// Resolves the "primary" member for a human account. account_id is nullable and
// NON-unique (an account that creates N orgs owns N member rows, and a re-joining
// human accumulates a dead member alongside a fresh one). A LIVE (authenticatable)
// member always wins over an offboarded (removed/purged/deactivated/suspended)
// one so a re-joined account resolves to its fresh membership, not the revoked
// ghost; among members of equal liveness the most-recent row is chosen for a
// deterministic identity.
func (q *Queries) memberByAccountID(ctx context.Context, accountID pgtype.UUID) (memberByAccountIDRow, error) {
	row := q.db.QueryRow(ctx, memberByAccountID, accountID)
	var i memberByAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberByAccountInOrg = `-- name: memberByAccountInOrg :one
SELECT m.id, m.email, m.display_name, m.first_name, m.last_name, m.git_handle, m.slack_user_id, m.telegram_chat_id, m.delivery_channel, m.status, m.created_at, m.updated_at, m.teams_user_id, m.discord_user_id, m.binding_error
FROM members m
JOIN project_members pm ON pm.member_id = m.id
JOIN projects p ON p.id = pm.project_id
WHERE m.account_id = $1 AND p.org_id = $2
ORDER BY (m.status IN ('removed', 'purged', 'deactivated', 'suspended')) ASC, m.created_at DESC
LIMIT 1
`

type memberByAccountInOrgParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	OrgID     pgtype.UUID `json:"org_id"`
}

type memberByAccountInOrgRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

// Org-scoped variant of memberByAccountID: the account's "primary" member WITHIN
// one org, resolved via the member's project memberships (project_members →
// projects.org_id). Backs the redeem idempotency guard, which must be org-scoped
// so an account that is a live member of org A can still redeem a join code for
// org B (a global ByAccountID would wrongly report "already member"). A LIVE
// (authenticatable) member wins over a dead (deactivated/suspended) one, then the
// most-recent row; removed/purged members no longer own project_members rows
// (offboard deletes them) so they never surface here at all. Returns ErrNotFound
// when the account owns no member participating in the org.
func (q *Queries) memberByAccountInOrg(ctx context.Context, arg memberByAccountInOrgParams) (memberByAccountInOrgRow, error) {
	row := q.db.QueryRow(ctx, memberByAccountInOrg, arg.AccountID, arg.OrgID)
	var i memberByAccountInOrgRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberByDiscordUserID = `-- name: memberByDiscordUserID :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE discord_user_id = $1
`

type memberByDiscordUserIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

// discord_user_id is NOT NULL DEFAULT ”; same empty-string caveat as
// memberByTeamsUserID above.
func (q *Queries) memberByDiscordUserID(ctx context.Context, discordUserID string) (memberByDiscordUserIDRow, error) {
	row := q.db.QueryRow(ctx, memberByDiscordUserID, discordUserID)
	var i memberByDiscordUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberByEmail = `-- name: memberByEmail :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE email = $1
`

type memberByEmailRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

func (q *Queries) memberByEmail(ctx context.Context, email pgtype.Text) (memberByEmailRow, error) {
	row := q.db.QueryRow(ctx, memberByEmail, email)
	var i memberByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberByID = `-- name: memberByID :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE id = $1
`

type memberByIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

func (q *Queries) memberByID(ctx context.Context, id uuid.UUID) (memberByIDRow, error) {
	row := q.db.QueryRow(ctx, memberByID, id)
	var i memberByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberBySlackUserID = `-- name: memberBySlackUserID :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE slack_user_id = $1
`

type memberBySlackUserIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

func (q *Queries) memberBySlackUserID(ctx context.Context, slackUserID string) (memberBySlackUserIDRow, error) {
	row := q.db.QueryRow(ctx, memberBySlackUserID, slackUserID)
	var i memberBySlackUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberByTeamsUserID = `-- name: memberByTeamsUserID :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE teams_user_id = $1
`

type memberByTeamsUserIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

// teams_user_id is NOT NULL DEFAULT ”; callers must never look up an empty
// string (it would match an arbitrary unbound member) — enforced in the
// adapter, not here.
func (q *Queries) memberByTeamsUserID(ctx context.Context, teamsUserID string) (memberByTeamsUserIDRow, error) {
	row := q.db.QueryRow(ctx, memberByTeamsUserID, teamsUserID)
	var i memberByTeamsUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberByTelegramChatID = `-- name: memberByTelegramChatID :one
SELECT id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
FROM members
WHERE telegram_chat_id = $1
`

type memberByTelegramChatIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

func (q *Queries) memberByTelegramChatID(ctx context.Context, telegramChatID string) (memberByTelegramChatIDRow, error) {
	row := q.db.QueryRow(ctx, memberByTelegramChatID, telegramChatID)
	var i memberByTelegramChatIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}

const memberOnboardingDismissed = `-- name: memberOnboardingDismissed :one
SELECT (onboarding_dismissed_at IS NOT NULL)::bool AS dismissed
FROM members
WHERE id = $1
`

// True once the member has permanently dismissed the Get-started onboarding
// (the flag is per-member and server-side, so the dismissal survives reloads
// and follows the member across devices).
func (q *Queries) memberOnboardingDismissed(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, memberOnboardingDismissed, id)
	var dismissed bool
	err := row.Scan(&dismissed)
	return dismissed, err
}

const offboardMember = `-- name: offboardMember :execrows
WITH target AS (
    SELECT
        m.id,
        m.account_id,
        NOT EXISTS (
            SELECT 1
            FROM project_members other_pm
            JOIN projects other_p ON other_p.id = other_pm.project_id
            WHERE other_pm.member_id = m.id
              AND other_p.org_id IS DISTINCT FROM $1
        ) AS terminal
    FROM members m
    WHERE m.id = $2
      AND $3::text IN ('removed', 'purged')
      AND EXISTS (
          SELECT 1
          FROM project_members target_pm
          JOIN projects target_p ON target_p.id = target_pm.project_id
          WHERE target_pm.member_id = m.id
            AND target_p.org_id = $1
      )
),
terminalized AS (
    UPDATE members
    SET status           = $3,
        email            = $4,
        display_name     = $5,
        slack_user_id    = '',
        telegram_chat_id = '',
        teams_user_id    = '',
        discord_user_id  = '',
        binding_error    = '',
        delivery_channel = 'dashboard',
        updated_at       = NOW()
    WHERE members.id IN (SELECT target.id FROM target WHERE target.terminal)
    RETURNING members.id
),
purge_project_members AS (
    DELETE FROM project_members pm
    USING projects p, target
    WHERE pm.project_id = p.id
      AND pm.member_id = target.id
      AND p.org_id = $1
),
purge_org_members AS (
    DELETE FROM org_members om
    USING target
    WHERE om.account_id = target.account_id
      AND om.org_id = $1
)
SELECT target.id FROM target
`

type offboardMemberParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ID          uuid.UUID   `json:"id"`
	Status      string      `json:"status"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

// Remove a member from exactly one organization. Project memberships and org
// authority are deleted only for $5. The shared members row is terminalized and
// its chat bindings are freed only when no membership in another organization
// remains; otherwise the identity stays live for those other organizations.
func (q *Queries) offboardMember(ctx context.Context, arg offboardMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, offboardMember,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.Email,
		arg.DisplayName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orgMemberByID = `-- name: orgMemberByID :one
SELECT
    m.id, m.email, m.display_name, m.first_name, m.last_name, m.git_handle,
    m.delivery_channel, m.slack_user_id, m.teams_user_id, m.telegram_chat_id,
    m.discord_user_id, m.binding_error, m.status, m.return_date,
    (m.account_id IS NULL)::bool AS external,
    COALESCE(om.role = 'admin', false)::bool AS is_org_admin,
    COALESCE(
        json_agg(json_build_object('project_id', pm.project_id, 'domains', pm.domains))
            FILTER (WHERE pm.project_id IS NOT NULL),
        '[]'
    )::jsonb AS projects
FROM members m
JOIN project_members pm ON pm.member_id = m.id
JOIN projects p ON p.id = pm.project_id AND p.org_id = $1
LEFT JOIN org_members om ON om.account_id = m.account_id AND om.org_id = $1
WHERE m.id = $2 AND m.status NOT IN ('removed', 'purged')
GROUP BY m.id, om.role
`

type orgMemberByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    uuid.UUID   `json:"id"`
}

type orgMemberByIDRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	DeliveryChannel string      `json:"delivery_channel"`
	SlackUserID     string      `json:"slack_user_id"`
	TeamsUserID     string      `json:"teams_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
	Status          string      `json:"status"`
	ReturnDate      pgtype.Date `json:"return_date"`
	External        bool        `json:"external"`
	IsOrgAdmin      bool        `json:"is_org_admin"`
	Projects        []byte      `json:"projects"`
}

// One member's rich record, scoped to the org (returns no row if the member is
// not part of the caller's org). Same shape as listOrgRoster.
func (q *Queries) orgMemberByID(ctx context.Context, arg orgMemberByIDParams) (orgMemberByIDRow, error) {
	row := q.db.QueryRow(ctx, orgMemberByID, arg.OrgID, arg.ID)
	var i orgMemberByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.DeliveryChannel,
		&i.SlackUserID,
		&i.TeamsUserID,
		&i.TelegramChatID,
		&i.DiscordUserID,
		&i.BindingError,
		&i.Status,
		&i.ReturnDate,
		&i.External,
		&i.IsOrgAdmin,
		&i.Projects,
	)
	return i, err
}

const reactivateRemovedMember = `-- name: reactivateRemovedMember :execrows
UPDATE members
SET status = 'invited', updated_at = NOW()
WHERE id = $1 AND status = 'removed'
`

// Re-invite a soft-removed member: flip the status back to invited so the
// invitation lifecycle (event + email) restarts. Guarded on 'removed' so
// purged members (PII gone) and active members are never touched.
func (q *Queries) reactivateRemovedMember(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateRemovedMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberActivation = `-- name: setMemberActivation :execrows
UPDATE members
SET status      = $2,
    return_date = NULL,
    updated_at  = NOW()
WHERE id = $1
  AND status NOT IN ('removed', 'purged')
`

type setMemberActivationParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Deactivate (off billing, not routable) or reactivate a member. Reversible.
// Never touches removed/purged rows.
func (q *Queries) setMemberActivation(ctx context.Context, arg setMemberActivationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberActivation, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberAvailability = `-- name: setMemberAvailability :execrows
UPDATE members
SET status      = $2,
    return_date = $3,
    updated_at  = NOW()
WHERE id = $1
  AND status IN ('active', 'on_leave', 'invited')
`

type setMemberAvailabilityParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	ReturnDate pgtype.Date `json:"return_date"`
}

// Flip a member between active and on_leave. return_date is stored only for
// on_leave (cleared otherwise). Guarded off deactivated/removed/purged so those
// lifecycle states are only changed through their own paths.
func (q *Queries) setMemberAvailability(ctx context.Context, arg setMemberAvailabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberAvailability, arg.ID, arg.Status, arg.ReturnDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberOnboardingDismissed = `-- name: setMemberOnboardingDismissed :execrows
UPDATE members
SET onboarding_dismissed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

// Mark the Get-started onboarding permanently dismissed for the member.
func (q *Queries) setMemberOnboardingDismissed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberOnboardingDismissed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMember = `-- name: updateMember :one
UPDATE members
SET display_name     = $2,
    slack_user_id    = $3,
    telegram_chat_id = $4,
    delivery_channel = $5,
    status           = $6,
    email            = $7,
    first_name       = $8,
    last_name        = $9,
    git_handle       = $10,
    -- NULL keeps the existing binding: an account link is only ever added,
    -- never cleared through this update.
    account_id       = COALESCE($11, account_id),
    teams_user_id    = $12,
    discord_user_id  = $13,
    binding_error    = $14,
    updated_at       = NOW()
WHERE id = $1
RETURNING id, email, display_name, first_name, last_name, git_handle, slack_user_id, telegram_chat_id, delivery_channel, status, created_at, updated_at, teams_user_id, discord_user_id, binding_error
`

type updateMemberParams struct {
	ID              uuid.UUID   `json:"id"`
	DisplayName     pgtype.Text `json:"display_name"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	Email           pgtype.Text `json:"email"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	AccountID       pgtype.UUID `json:"account_id"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

type updateMemberRow struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	GitHandle       string      `json:"git_handle"`
	SlackUserID     string      `json:"slack_user_id"`
	TelegramChatID  string      `json:"telegram_chat_id"`
	DeliveryChannel string      `json:"delivery_channel"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	TeamsUserID     string      `json:"teams_user_id"`
	DiscordUserID   string      `json:"discord_user_id"`
	BindingError    string      `json:"binding_error"`
}

func (q *Queries) updateMember(ctx context.Context, arg updateMemberParams) (updateMemberRow, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.DisplayName,
		arg.SlackUserID,
		arg.TelegramChatID,
		arg.DeliveryChannel,
		arg.Status,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.GitHandle,
		arg.AccountID,
		arg.TeamsUserID,
		arg.DiscordUserID,
		arg.BindingError,
	)
	var i updateMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.GitHandle,
		&i.SlackUserID,
		&i.TelegramChatID,
		&i.DeliveryChannel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamsUserID,
		&i.DiscordUserID,
		&i.BindingError,
	)
	return i, err
}
