// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_members_queries.sql

package identity

import (
	"context"

	"github.com/google/uuid"
)

const addOrgMember = `-- name: addOrgMember :exec

INSERT INTO org_members (org_id, account_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, account_id) DO UPDATE
    SET role = EXCLUDED.role
`

type addOrgMemberParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	AccountID uuid.UUID `json:"account_id"`
	Role      string    `json:"role"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) addOrgMember(ctx context.Context, arg addOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.OrgID, arg.AccountID, arg.Role)
	return err
}

const countInstanceSeats = `-- name: countInstanceSeats :one
SELECT COUNT(DISTINCT account_id) FROM org_members
`

// Instance-wide seat count for a licensed self-host: distinct billable persons
// (accounts that are a member of any org). Backs the Licensed edition seat cap
// (1 instance = 1 customer = N seats, all orgs combined).
func (q *Queries) countInstanceSeats(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstanceSeats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgAdmins = `-- name: countOrgAdmins :one
SELECT COUNT(*) FROM org_members WHERE org_id = $1 AND role = 'admin'
`

func (q *Queries) countOrgAdmins(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgAdmins, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const orgMemberRole = `-- name: orgMemberRole :one
SELECT role
FROM org_members
WHERE org_id = $1 AND account_id = $2
LIMIT 1
`

type orgMemberRoleParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) orgMemberRole(ctx context.Context, arg orgMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, orgMemberRole, arg.OrgID, arg.AccountID)
	var role string
	err := row.Scan(&role)
	return role, err
}
