// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations_queries.sql

package identity

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrganizations = `-- name: countOrganizations :one
SELECT COUNT(*) FROM organizations
`

// Total organizations in the instance. Backs the Community-edition 1-org cap.
func (q *Queries) countOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: createOrganization :one

INSERT INTO organizations (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type createOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type createOrganizationRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createOrganization(ctx context.Context, arg createOrganizationParams) (createOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name)
	var i createOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const organizationByID = `-- name: organizationByID :one
SELECT id, name, created_at, updated_at
FROM organizations
WHERE id = $1
`

type organizationByIDRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) organizationByID(ctx context.Context, id uuid.UUID) (organizationByIDRow, error) {
	row := q.db.QueryRow(ctx, organizationByID, id)
	var i organizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: updateOrganization :one
UPDATE organizations
SET name       = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type updateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type updateOrganizationRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) updateOrganization(ctx context.Context, arg updateOrganizationParams) (updateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name)
	var i updateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
