// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_queries.sql

package identity

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByOrg = `-- name: countProjectsByOrg :one
SELECT COUNT(*) FROM projects
WHERE org_id = $1
`

// Projects owned by an org. Backs the Community-edition 1-project cap.
func (q *Queries) countProjectsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: createProject :one

INSERT INTO projects (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type createProjectParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type createProjectRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) createProject(ctx context.Context, arg createProjectParams) (createProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.Name)
	var i createProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectInOrg = `-- name: createProjectInOrg :exec
INSERT INTO projects (id, name, org_id)
VALUES ($1, $2, $3)
`

type createProjectInOrgParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

// Creates a project that is already attached to an organization. org_id must not
// be nil; the handler validates this before calling the store.
func (q *Queries) createProjectInOrg(ctx context.Context, arg createProjectInOrgParams) error {
	_, err := q.db.Exec(ctx, createProjectInOrg, arg.ID, arg.Name, arg.OrgID)
	return err
}

const projectByID = `-- name: projectByID :one
SELECT id, name, org_id, archived_at, created_at, updated_at
FROM projects
WHERE id = $1
`

type projectByIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	OrgID      pgtype.UUID        `json:"org_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

func (q *Queries) projectByID(ctx context.Context, id uuid.UUID) (projectByIDRow, error) {
	row := q.db.QueryRow(ctx, projectByID, id)
	var i projectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
