// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members_queries.sql

package identity

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: addProjectMember :exec

INSERT INTO project_members (project_id, member_id, domains)
VALUES ($1, $2, $3)
`

type addProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	MemberID  uuid.UUID `json:"member_id"`
	Domains   []string  `json:"domains"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) addProjectMember(ctx context.Context, arg addProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.MemberID, arg.Domains)
	return err
}

const addProjectMemberIdempotent = `-- name: addProjectMemberIdempotent :execrows
INSERT INTO project_members (project_id, member_id, domains)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, member_id) DO NOTHING
`

type addProjectMemberIdempotentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	MemberID  uuid.UUID `json:"member_id"`
	Domains   []string  `json:"domains"`
}

// Insert-or-skip variant for the find-or-create invite path: a duplicate
// membership must not abort the surrounding transaction, so the conflict is
// absorbed in SQL and detected via the affected-row count (0 = already member).
func (q *Queries) addProjectMemberIdempotent(ctx context.Context, arg addProjectMemberIdempotentParams) (int64, error) {
	result, err := q.db.Exec(ctx, addProjectMemberIdempotent, arg.ProjectID, arg.MemberID, arg.Domains)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectMembersByProject = `-- name: projectMembersByProject :many
SELECT project_id, member_id, domains, created_at
FROM project_members
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) projectMembersByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, projectMembersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ProjectID,
			&i.MemberID,
			&i.Domains,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMembersMissingSlackBinding = `-- name: projectMembersMissingSlackBinding :many
SELECT m.id, m.email
FROM project_members pm
JOIN members m ON m.id = pm.member_id
WHERE pm.project_id = $1
  AND m.email IS NOT NULL AND m.email <> ''
  AND m.slack_user_id = ''
ORDER BY m.created_at ASC
`

type projectMembersMissingSlackBindingRow struct {
	ID    uuid.UUID   `json:"id"`
	Email pgtype.Text `json:"email"`
}

// Members on the project with an email but no Slack binding yet — the backfill
// set for Slack auto-bind (SyncChatDirectory).
func (q *Queries) projectMembersMissingSlackBinding(ctx context.Context, projectID uuid.UUID) ([]projectMembersMissingSlackBindingRow, error) {
	rows, err := q.db.Query(ctx, projectMembersMissingSlackBinding, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []projectMembersMissingSlackBindingRow{}
	for rows.Next() {
		var i projectMembersMissingSlackBindingRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainsForMember = `-- name: setDomainsForMember :execrows
UPDATE project_members
SET domains = $2
WHERE member_id = $1
`

type setDomainsForMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Domains  []string  `json:"domains"`
}

// Self-serve expertise: replace a member's domains across ALL their project
// memberships in one statement. Scope is the member (not one project), so an
// onboarding member can set their own expertise without touching another
// membership. Returns the number of memberships updated.
func (q *Queries) setDomainsForMember(ctx context.Context, arg setDomainsForMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDomainsForMember, arg.MemberID, arg.Domains)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProjectMemberDomains = `-- name: updateProjectMemberDomains :execrows
UPDATE project_members
SET domains = $3
WHERE project_id = $1 AND member_id = $2
`

type updateProjectMemberDomainsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	MemberID  uuid.UUID `json:"member_id"`
	Domains   []string  `json:"domains"`
}

func (q *Queries) updateProjectMemberDomains(ctx context.Context, arg updateProjectMemberDomainsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProjectMemberDomains, arg.ProjectID, arg.MemberID, arg.Domains)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
