// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   uuid.UUID   `json:"id"`
	Subject              pgtype.Text `json:"subject"`
	Email                string      `json:"email"`
	DisplayName          pgtype.Text `json:"display_name"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	PasswordHash         pgtype.Text `json:"password_hash"`
	PasswordResetVersion int32       `json:"password_reset_version"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"project_id"`
	MemberID  uuid.UUID `json:"member_id"`
	Domains   []string  `json:"domains"`
	CreatedAt time.Time `json:"created_at"`
}
