// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	accountByEmail(ctx context.Context, email string) (Account, error)
	accountByID(ctx context.Context, id uuid.UUID) (Account, error)
	accountBySubject(ctx context.Context, subject pgtype.Text) (Account, error)
	// Returns the id + password hash for email+password login. password_hash is NULL
	// for IdP-only accounts (the caller must treat that as "no local password").
	accountCredentialByEmail(ctx context.Context, email string) (accountCredentialByEmailRow, error)
	// The current password_reset_version for a local account, keyed by email. Used to
	// stamp a reset token so it can be invalidated (single-use / on password change).
	accountResetVersionByEmail(ctx context.Context, email string) (accountResetVersionByEmailRow, error)
	// The org's current live token, if any. adaptererr.ErrNotFound (no row) when the
	// org has never generated one or the last one was revoked.
	activeJoinTokenByOrg(ctx context.Context, orgID uuid.UUID) (activeJoinTokenByOrgRow, error)
	// Counts the distinct active persons in an org: every account in org_members
	// (the logins) whose in-org member is not deactivated, plus every external-only
	// member (no linked account) participating in one of the org's NON-ARCHIVED
	// projects. Deactivated, removed and purged members are excluded — deactivation
	// frees the slot for reuse. An external-only member whose every project is
	// archived is likewise excluded (they route nowhere); a member with at least one
	// active project still counts even if they also sit in an archived one.
	activeMemberCountByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	addOrgMember(ctx context.Context, arg addOrgMemberParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	addProjectMember(ctx context.Context, arg addProjectMemberParams) error
	// Insert-or-skip variant for the find-or-create invite path: a duplicate
	// membership must not abort the surrounding transaction, so the conflict is
	// absorbed in SQL and detected via the affected-row count (0 = already member).
	addProjectMemberIdempotent(ctx context.Context, arg addProjectMemberIdempotentParams) (int64, error)
	// Undo the dismissal (the Get-started page + nav item come back).
	clearMemberOnboardingDismissed(ctx context.Context, id uuid.UUID) (int64, error)
	// Instance-wide seat count for a licensed self-host: distinct billable persons
	// (accounts that are a member of any org). Backs the Licensed edition seat cap
	// (1 instance = 1 customer = N seats, all orgs combined).
	countInstanceSeats(ctx context.Context) (int64, error)
	countOrgAdmins(ctx context.Context, orgID uuid.UUID) (int64, error)
	// Total organizations in the instance. Backs the Community-edition 1-org cap.
	countOrganizations(ctx context.Context) (int64, error)
	// Projects owned by an org. Backs the Community-edition 1-project cap.
	countProjectsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createAccount(ctx context.Context, arg createAccountParams) (Account, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Inserts a fresh join token. The caller (CreateJoinToken store method) revokes
	// any prior live token for the org in the same transaction first, so the partial
	// unique index (one live token per org) is never violated.
	createJoinToken(ctx context.Context, arg createJoinTokenParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createMember(ctx context.Context, arg createMemberParams) (createMemberRow, error)
	// Creates a member linked to a human account (active, dashboard-channel). Used by
	// the CreateOrganization compound store; the account must exist before calling this.
	createMemberWithAccount(ctx context.Context, arg createMemberWithAccountParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createOrganization(ctx context.Context, arg createOrganizationParams) (createOrganizationRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	createProject(ctx context.Context, arg createProjectParams) (createProjectRow, error)
	// Creates a project that is already attached to an organization. org_id must not
	// be nil; the handler validates this before calling the store.
	createProjectInOrg(ctx context.Context, arg createProjectInOrgParams) error
	// Resolves a token to its org/project and whether it has been revoked. The
	// org/project a redemption lands in come ONLY from this row.
	joinTokenByToken(ctx context.Context, token string) (joinTokenByTokenRow, error)
	// Rich org roster: every member participating in one of the org's projects, with
	// identity, channel + bindings, status, return_date, org-admin flag, external
	// flag, and their per-project expertise tags as a JSON array of
	// {project_id, domains}. The pendingOnly flag ($2) splits the two complementary
	// audiences from one query body:
	//   * pendingOnly = false → the roster everyone sees: removed/purged AND the
	//     `pending` self-join redeemers (join-code, awaiting approval) are excluded.
	//   * pendingOnly = true  → admin-only: ONLY the `pending` members, backing the
	//     Team page's "Invited" group.
	// The application handler calls it twice (see list_members.go) and appends the
	// pending set to the roster only for an org admin (RBAC gate in server.go).
	listOrgRoster(ctx context.Context, arg listOrgRosterParams) ([]listOrgRosterRow, error)
	memberAccountID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error)
	// Resolves the "primary" member for a human account. account_id is nullable and
	// NON-unique (an account that creates N orgs owns N member rows, and a re-joining
	// human accumulates a dead member alongside a fresh one). A LIVE (authenticatable)
	// member always wins over an offboarded (removed/purged/deactivated/suspended)
	// one so a re-joined account resolves to its fresh membership, not the revoked
	// ghost; among members of equal liveness the most-recent row is chosen for a
	// deterministic identity.
	memberByAccountID(ctx context.Context, accountID pgtype.UUID) (memberByAccountIDRow, error)
	// Org-scoped variant of memberByAccountID: the account's "primary" member WITHIN
	// one org, resolved via the member's project memberships (project_members →
	// projects.org_id). Backs the redeem idempotency guard, which must be org-scoped
	// so an account that is a live member of org A can still redeem a join code for
	// org B (a global ByAccountID would wrongly report "already member"). A LIVE
	// (authenticatable) member wins over a dead (deactivated/suspended) one, then the
	// most-recent row; removed/purged members no longer own project_members rows
	// (offboard deletes them) so they never surface here at all. Returns ErrNotFound
	// when the account owns no member participating in the org.
	memberByAccountInOrg(ctx context.Context, arg memberByAccountInOrgParams) (memberByAccountInOrgRow, error)
	// discord_user_id is NOT NULL DEFAULT ''; same empty-string caveat as
	// memberByTeamsUserID above.
	memberByDiscordUserID(ctx context.Context, discordUserID string) (memberByDiscordUserIDRow, error)
	memberByEmail(ctx context.Context, email pgtype.Text) (memberByEmailRow, error)
	memberByID(ctx context.Context, id uuid.UUID) (memberByIDRow, error)
	memberBySlackUserID(ctx context.Context, slackUserID string) (memberBySlackUserIDRow, error)
	// teams_user_id is NOT NULL DEFAULT ''; callers must never look up an empty
	// string (it would match an arbitrary unbound member) — enforced in the
	// adapter, not here.
	memberByTeamsUserID(ctx context.Context, teamsUserID string) (memberByTeamsUserIDRow, error)
	memberByTelegramChatID(ctx context.Context, telegramChatID string) (memberByTelegramChatIDRow, error)
	// True once the member has permanently dismissed the Get-started onboarding
	// (the flag is per-member and server-side, so the dismissal survives reloads
	// and follows the member across devices).
	memberOnboardingDismissed(ctx context.Context, id uuid.UUID) (bool, error)
	// Remove a member from exactly one organization. Project memberships and org
	// authority are deleted only for $5. The shared members row is terminalized and
	// its chat bindings are freed only when no membership in another organization
	// remains; otherwise the identity stays live for those other organizations.
	offboardMember(ctx context.Context, arg offboardMemberParams) (int64, error)
	// One member's rich record, scoped to the org (returns no row if the member is
	// not part of the caller's org). Same shape as listOrgRoster.
	orgMemberByID(ctx context.Context, arg orgMemberByIDParams) (orgMemberByIDRow, error)
	orgMemberRole(ctx context.Context, arg orgMemberRoleParams) (string, error)
	organizationByID(ctx context.Context, id uuid.UUID) (organizationByIDRow, error)
	projectByID(ctx context.Context, id uuid.UUID) (projectByIDRow, error)
	projectMembersByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error)
	// Members on the project with an email but no Slack binding yet — the backfill
	// set for Slack auto-bind (SyncChatDirectory).
	projectMembersMissingSlackBinding(ctx context.Context, projectID uuid.UUID) ([]projectMembersMissingSlackBindingRow, error)
	// Re-invite a soft-removed member: flip the status back to invited so the
	// invitation lifecycle (event + email) restarts. Guarded on 'removed' so
	// purged members (PII gone) and active members are never touched.
	reactivateRemovedMember(ctx context.Context, id uuid.UUID) (int64, error)
	// Atomically spends a reset-token version while replacing the password. A
	// concurrent replay, unknown account, or IdP-only account returns no row.
	resetAccountPassword(ctx context.Context, arg resetAccountPasswordParams) (uuid.UUID, error)
	// Revokes the org's live (non-revoked) token(s). Used both to rotate before a
	// fresh insert and by an explicit revoke. Idempotent: revokes nothing when the
	// org has no live token.
	revokeLiveOrgJoinTokens(ctx context.Context, orgID uuid.UUID) (int64, error)
	// Sets (or clears) the bcrypt password hash for a local-auth account.
	setAccountPassword(ctx context.Context, arg setAccountPasswordParams) error
	// Self-serve expertise: replace a member's domains across ALL their project
	// memberships in one statement. Scope is the member (not one project), so an
	// onboarding member can set their own expertise without touching another
	// membership. Returns the number of memberships updated.
	setDomainsForMember(ctx context.Context, arg setDomainsForMemberParams) (int64, error)
	// Deactivate (off billing, not routable) or reactivate a member. Reversible.
	// Never touches removed/purged rows.
	setMemberActivation(ctx context.Context, arg setMemberActivationParams) (int64, error)
	// Flip a member between active and on_leave. return_date is stored only for
	// on_leave (cleared otherwise). Guarded off deactivated/removed/purged so those
	// lifecycle states are only changed through their own paths.
	setMemberAvailability(ctx context.Context, arg setMemberAvailabilityParams) (int64, error)
	// Mark the Get-started onboarding permanently dismissed for the member.
	setMemberOnboardingDismissed(ctx context.Context, id uuid.UUID) (int64, error)
	updateMember(ctx context.Context, arg updateMemberParams) (updateMemberRow, error)
	updateOrganization(ctx context.Context, arg updateOrganizationParams) (updateOrganizationRow, error)
	updateProjectMemberDomains(ctx context.Context, arg updateProjectMemberDomainsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
