// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presence_queries.sql

package presence

import (
	"context"

	"github.com/google/uuid"
)

const presenceByMember = `-- name: presenceByMember :one
SELECT member_id, online, updated_at
FROM presence
WHERE member_id = $1
`

func (q *Queries) presenceByMember(ctx context.Context, memberID uuid.UUID) (Presence, error) {
	row := q.db.QueryRow(ctx, presenceByMember, memberID)
	var i Presence
	err := row.Scan(&i.MemberID, &i.Online, &i.UpdatedAt)
	return i, err
}

const upsertPresence = `-- name: upsertPresence :one

INSERT INTO presence (member_id, online, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (member_id)
DO UPDATE SET online = EXCLUDED.online, updated_at = NOW()
RETURNING member_id, online, updated_at
`

type upsertPresenceParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Online   bool      `json:"online"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) upsertPresence(ctx context.Context, arg upsertPresenceParams) (Presence, error) {
	row := q.db.QueryRow(ctx, upsertPresence, arg.MemberID, arg.Online)
	var i Presence
	err := row.Scan(&i.MemberID, &i.Online, &i.UpdatedAt)
	return i, err
}
