// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package presence

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	presenceByMember(ctx context.Context, memberID uuid.UUID) (Presence, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	upsertPresence(ctx context.Context, arg upsertPresenceParams) (Presence, error)
}

var _ Querier = (*Queries)(nil)
