// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package presence

import (
	"time"

	"github.com/google/uuid"
)

type Presence struct {
	MemberID  uuid.UUID `json:"member_id"`
	Online    bool      `json:"online"`
	UpdatedAt time.Time `json:"updated_at"`
}
