// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_messages_queries.sql

package integration

import (
	"context"

	"github.com/google/uuid"
)

const finalizeProviderMessage = `-- name: finalizeProviderMessage :execrows
UPDATE provider_messages
SET channel_id = $2, message_ref = $3, state = $4, updated_at = NOW()
WHERE id = $1 AND state = 'reserving'
`

type finalizeProviderMessageParams struct {
	ID         uuid.UUID `json:"id"`
	ChannelID  string    `json:"channel_id"`
	MessageRef string    `json:"message_ref"`
	State      string    `json:"state"`
}

// Closes the reserve→deliver→finalize window for the pool fan-out: a row
// written as 'reserving' (no channel/ref yet, before Deliver ever ran) is
// finalized here with the channel/ref Deliver actually returned, in the same
// write as its state transition (normally to 'posted'). Guarded on the row
// still being 'reserving' so this can never regress a row a concurrent path
// already finalized or advanced past.
func (q *Queries) finalizeProviderMessage(ctx context.Context, arg finalizeProviderMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeProviderMessage,
		arg.ID,
		arg.ChannelID,
		arg.MessageRef,
		arg.State,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const providerMessageByChannelRef = `-- name: providerMessageByChannelRef :one
SELECT id, conversation_id, member_id, provider_kind, channel_id, message_ref, state, created_at, updated_at
FROM provider_messages
WHERE channel_id = $1 AND message_ref = $2
ORDER BY created_at DESC
LIMIT 1
`

type providerMessageByChannelRefParams struct {
	ChannelID  string `json:"channel_id"`
	MessageRef string `json:"message_ref"`
}

// Inbound correlation: a reply's (channel, message ref) resolves back to its
// conversation/member pair when the direct conversations-thread lookup misses
// (the pool path never writes conversations.slack_thread_ts).
func (q *Queries) providerMessageByChannelRef(ctx context.Context, arg providerMessageByChannelRefParams) (ProviderMessage, error) {
	row := q.db.QueryRow(ctx, providerMessageByChannelRef, arg.ChannelID, arg.MessageRef)
	var i ProviderMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MemberID,
		&i.ProviderKind,
		&i.ChannelID,
		&i.MessageRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const providerMessageLatestByChannel = `-- name: providerMessageLatestByChannel :one
SELECT id, conversation_id, member_id, provider_kind, channel_id, message_ref, state, created_at, updated_at
FROM provider_messages
WHERE channel_id = $1 AND state IN ('posted', 'claimed_won')
ORDER BY updated_at DESC
LIMIT 1
`

// Inbound correlation for providers whose conversation model has no stable
// per-message reference to key an exact (channel, ref) match on (Microsoft
// Teams personal chats: every message in the 1:1 conversation shares the same
// conversation id, with no thread/reply id the client reliably sets). Picks
// the most recently updated still-open row for the channel; a member with two
// concurrent unclaimed pool questions on the same channel is a known,
// accepted ambiguity (the newer one wins the reply).
func (q *Queries) providerMessageLatestByChannel(ctx context.Context, channelID string) (ProviderMessage, error) {
	row := q.db.QueryRow(ctx, providerMessageLatestByChannel, channelID)
	var i ProviderMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MemberID,
		&i.ProviderKind,
		&i.ChannelID,
		&i.MessageRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const providerMessagesByConversation = `-- name: providerMessagesByConversation :many
SELECT id, conversation_id, member_id, provider_kind, channel_id, message_ref, state, created_at, updated_at
FROM provider_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) providerMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]ProviderMessage, error) {
	rows, err := q.db.Query(ctx, providerMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderMessage{}
	for rows.Next() {
		var i ProviderMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MemberID,
			&i.ProviderKind,
			&i.ChannelID,
			&i.MessageRef,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderMessageState = `-- name: setProviderMessageState :execrows
UPDATE provider_messages
SET state = $2, updated_at = NOW()
WHERE id = $1
`

type setProviderMessageStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) setProviderMessageState(ctx context.Context, arg setProviderMessageStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderMessageState, arg.ID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProviderMessage = `-- name: upsertProviderMessage :execrows

INSERT INTO provider_messages (id, conversation_id, member_id, provider_kind, channel_id, message_ref, state)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (conversation_id, member_id) DO NOTHING
`

type upsertProviderMessageParams struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberID       uuid.UUID `json:"member_id"`
	ProviderKind   string    `json:"provider_kind"`
	ChannelID      string    `json:"channel_id"`
	MessageRef     string    `json:"message_ref"`
	State          string    `json:"state"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// The delivery ledger: one row per (conversation, member) pool DM, keyed for
// idempotent re-delivery and inbound correlation by (channel, message ref).
// ON CONFLICT DO NOTHING, not DO UPDATE: the first successfully-recorded
// delivery for a (conversation, member) pair must never be overwritten by a
// later call — a replayed CONVERSATION_OPENED (at-least-once redelivery)
// would otherwise regress a row already at claimed_won/claimed_lost/released/
// resolved back to "posted", re-arming the projector's state guards and
// letting a second claim/release cycle run. The application layer
// (delivery_notifier.go) already skips re-delivering to a candidate with an
// existing row; this is the defense-in-depth backstop, and it must be a
// pure no-op on conflict, never a write.
func (q *Queries) upsertProviderMessage(ctx context.Context, arg upsertProviderMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProviderMessage,
		arg.ID,
		arg.ConversationID,
		arg.MemberID,
		arg.ProviderKind,
		arg.ChannelID,
		arg.MessageRef,
		arg.State,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
