// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integration

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Closes the reserve→deliver→finalize window for the pool fan-out: a row
	// written as 'reserving' (no channel/ref yet, before Deliver ever ran) is
	// finalized here with the channel/ref Deliver actually returned, in the same
	// write as its state transition (normally to 'posted'). Guarded on the row
	// still being 'reserving' so this can never regress a row a concurrent path
	// already finalized or advanced past.
	finalizeProviderMessage(ctx context.Context, arg finalizeProviderMessageParams) (int64, error)
	// Inbound correlation: a reply's (channel, message ref) resolves back to its
	// conversation/member pair when the direct conversations-thread lookup misses
	// (the pool path never writes conversations.slack_thread_ts).
	providerMessageByChannelRef(ctx context.Context, arg providerMessageByChannelRefParams) (ProviderMessage, error)
	// Inbound correlation for providers whose conversation model has no stable
	// per-message reference to key an exact (channel, ref) match on (Microsoft
	// Teams personal chats: every message in the 1:1 conversation shares the same
	// conversation id, with no thread/reply id the client reliably sets). Picks
	// the most recently updated still-open row for the channel; a member with two
	// concurrent unclaimed pool questions on the same channel is a known,
	// accepted ambiguity (the newer one wins the reply).
	providerMessageLatestByChannel(ctx context.Context, channelID string) (ProviderMessage, error)
	providerMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]ProviderMessage, error)
	setProviderMessageState(ctx context.Context, arg setProviderMessageStateParams) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// The delivery ledger: one row per (conversation, member) pool DM, keyed for
	// idempotent re-delivery and inbound correlation by (channel, message ref).
	// ON CONFLICT DO NOTHING, not DO UPDATE: the first successfully-recorded
	// delivery for a (conversation, member) pair must never be overwritten by a
	// later call — a replayed CONVERSATION_OPENED (at-least-once redelivery)
	// would otherwise regress a row already at claimed_won/claimed_lost/released/
	// resolved back to "posted", re-arming the projector's state guards and
	// letting a second claim/release cycle run. The application layer
	// (delivery_notifier.go) already skips re-delivering to a candidate with an
	// existing row; this is the defense-in-depth backstop, and it must be a
	// pure no-op on conflict, never a write.
	upsertProviderMessage(ctx context.Context, arg upsertProviderMessageParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
