// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integration

import (
	"time"

	"github.com/google/uuid"
)

type ProviderMessage struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberID       uuid.UUID `json:"member_id"`
	ProviderKind   string    `json:"provider_kind"`
	ChannelID      string    `json:"channel_id"`
	MessageRef     string    `json:"message_ref"`
	State          string    `json:"state"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
