// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: license_queries.sql

package licensing

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInstanceLicense = `-- name: deleteInstanceLicense :exec
DELETE FROM instance_license WHERE singleton = TRUE
`

// Clears the stored license (revert to Community). Idempotent: a clear with no
// row is a no-op, not an error.
func (q *Queries) deleteInstanceLicense(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteInstanceLicense)
	return err
}

const getInstanceLicense = `-- name: getInstanceLicense :one

SELECT license_key, set_by, set_at
FROM instance_license
WHERE singleton = TRUE
`

type getInstanceLicenseRow struct {
	LicenseKey string      `json:"license_key"`
	SetBy      pgtype.UUID `json:"set_by"`
	SetAt      time.Time   `json:"set_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// The single stored license row, if any. adaptererr.ErrNotFound (no row) when no
// key has ever been set — the fail-safe boot path treats that miss as Community.
func (q *Queries) getInstanceLicense(ctx context.Context) (getInstanceLicenseRow, error) {
	row := q.db.QueryRow(ctx, getInstanceLicense)
	var i getInstanceLicenseRow
	err := row.Scan(&i.LicenseKey, &i.SetBy, &i.SetAt)
	return i, err
}

const upsertInstanceLicense = `-- name: upsertInstanceLicense :exec
INSERT INTO instance_license (singleton, license_key, set_by, set_at)
VALUES (TRUE, $1, $2, NOW())
ON CONFLICT (singleton)
DO UPDATE SET license_key = EXCLUDED.license_key, set_by = EXCLUDED.set_by, set_at = NOW()
`

type upsertInstanceLicenseParams struct {
	LicenseKey string      `json:"license_key"`
	SetBy      pgtype.UUID `json:"set_by"`
}

// Stores (or replaces) the one license row. The singleton PRIMARY KEY makes this
// an upsert against the single row: a fresh paste, a Replace, and a refresh-loop
// renewal all land here.
func (q *Queries) upsertInstanceLicense(ctx context.Context, arg upsertInstanceLicenseParams) error {
	_, err := q.db.Exec(ctx, upsertInstanceLicense, arg.LicenseKey, arg.SetBy)
	return err
}
