// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package licensing

import (
	"context"
)

type Querier interface {
	// Clears the stored license (revert to Community). Idempotent: a clear with no
	// row is a no-op, not an error.
	deleteInstanceLicense(ctx context.Context) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// The single stored license row, if any. adaptererr.ErrNotFound (no row) when no
	// key has ever been set — the fail-safe boot path treats that miss as Community.
	getInstanceLicense(ctx context.Context) (getInstanceLicenseRow, error)
	// Stores (or replaces) the one license row. The singleton PRIMARY KEY makes this
	// an upsert against the single row: a fresh paste, a Replace, and a refresh-loop
	// renewal all land here.
	upsertInstanceLicense(ctx context.Context, arg upsertInstanceLicenseParams) error
}

var _ Querier = (*Queries)(nil)
