#!/usr/bin/env bash
# Generate a self-host .env with strong random secrets. Run once from the repo
# root: `bash scripts/bootstrap.sh [BASE_URL] [ADMIN_EMAIL]`. Refuses to clobber an
# existing .env (regenerating ORAKO_AUTH_HS256_SECRET after first boot logs
# everyone out).
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo "refusing to overwrite an existing .env — edit it by hand or delete it first" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets" >&2
  exit 1
fi

BASE_URL="${1:-http://localhost:8080}"
ADMIN_EMAIL="${2:-admin@example.com}"
# First-admin password: generated so the instance is reachable out of the box.
# The admin can change it from the dashboard (Account → password / forgot-password)
# after first login.
ADMIN_PASSWORD="$(openssl rand -base64 18)"

umask 077
cat > .env <<EOF
# Generated by scripts/bootstrap.sh — self-host defaults. KEEP SECRET.
# Do NOT change ORAKO_AUTH_HS256_SECRET after first boot: it invalidates every
# existing session.

# --- Postgres ---
POSTGRES_USER=orako
POSTGRES_DB=orako
POSTGRES_PASSWORD=$(openssl rand -hex 24)

# --- Server ---
ORAKO_HTTP_PORT=8080
ORAKO_BASE_URL=${BASE_URL}

# --- Auth (self-host: server is its own identity provider) ---
ORAKO_AUTH_MODE=local
ORAKO_AUTH_HS256_SECRET=$(openssl rand -hex 32)
# Issuer + audience are baked into (and verified on) the session tokens the server
# mints. Any stable values work; both are REQUIRED in local mode (fail-closed boot).
ORAKO_AUTH_ISSUER=${BASE_URL}
ORAKO_AUTH_AUDIENCE=orako-dashboard
# First admin, seeded once on boot (idempotent). Log in with these, then invite
# teammates from the dashboard. Change ADMIN_EMAIL before first boot if you like;
# after first boot this seed is a no-op (the account already exists).
ORAKO_ADMIN_EMAIL=${ADMIN_EMAIL}
ORAKO_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# --- Email (optional but recommended) ---
# Invites and password-reset links need SMTP; without it those emails silently
# do not send (you can still log in as the seeded admin).
# ORAKO_SMTP_HOST=
# ORAKO_SMTP_PORT=587
# ORAKO_SMTP_USERNAME=
# ORAKO_SMTP_PASSWORD=
# ORAKO_SMTP_FROM=Orako <no-reply@orako.example.com>

# --- Edition ---
# Unlicensed = free Community edition: 5 members / 1 org / 1 project.
# To raise the caps, paste a signed license key in the dashboard under
# Settings → License (stored in the DB, applied instantly — no env var, no
# restart). The signing public key is baked into the binary (see .env.example →
# "License / edition").
EOF
chmod 600 .env

echo "Wrote .env (chmod 600) for base URL: ${BASE_URL}"
echo
echo "  Admin login (seeded on first boot):"
echo "    email:    ${ADMIN_EMAIL}"
echo "    password: ${ADMIN_PASSWORD}"
echo "  ^ save this now — it is only printed here. Change it after first login."
echo
echo "Next:  docker compose up  →  open ${BASE_URL}  →  sign in as the admin above"
echo "Note:  invites + password reset need SMTP (ORAKO_SMTP_* in .env)."
echo "       Search is built in (Postgres FTS + pg_trgm) — no model to provision."
